import {siteFetch as fetch,currentSite,apiOrigin,localLink,startGoogle,clearSession,saveSession} from './site-context.js?v=20261010-cover';
import {mountLiveGifts} from './live-gifts.js?v=20261010-cover';
import {liveShareButton} from './live-share.js?v=20261010-cover';
import {mountMediaPlayer} from './mediamtx-player.js?v=20261010-cover';
import {openPhoneStudio,openGuestStudio} from './browser-live.js?v=20261010-cover';
import {botCheck} from './bot-check.js?v=20261010-cover';
import {openSignIn} from './shared-login.js?v=20261010-cover';
import {el} from './rr-addon-render.js?v=20261010-cover';
const brands={richrow:['Rich Row Records','https://richrowmusic.com'],waynekastro:['Wayne Kastro','https://waynekastro.com'],dracodon17:['Draco Don17','https://dracodon17.com'],goldenrama440:['Golden Rama','https://goldenrama440.com']};
const q=new URLSearchParams(location.search),site=Object.hasOwn(brands,q.get('site'))?q.get('site'):'richrow',ownerMode=q.get('manage')==='1',admin=false;
const main=document.querySelector('main'),dialog=document.querySelector('dialog'),notice=document.querySelector('#notice'),nav=document.querySelector('#portal-nav');
let phoneStudio,pendingGuestInvite=new URLSearchParams(location.hash.slice(1)).get('invite');
let liveGiftsUI;
let token=sessionStorage.getItem('rr_artist_token')||'',authConfig,model={records:[],assets:[],access:[]},config={},tab=admin&&['access','releases','messages','posts','live','statistics'].includes(q.get('tab'))?q.get('tab'):q.get('tab')==='statistics'?'statistics':q.get('watch')?'watch':q.get('feed')||document.body.dataset.feed==='1'?'feed':'home',room,player,preview,heartbeatTimer,watchTimer,chatTimer,noticeTimer,editing=false;
const say=t=>{notice.textContent=t;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.textContent='',15000);};
const btn=(t,fn,cls='')=>el('button',{type:'button',class:cls,onclick:async e=>{const b=e.currentTarget;b.disabled=true;try{await fn();}catch(err){say(err.message);}finally{b.disabled=false;}}},t);
const link=(t,href,cls='cta secondary')=>el('a',{href,class:cls},t);
const field=(name,label,value='',type='text')=>el('label',{},label,el(type==='textarea'?'textarea':'input',{name,type:type==='textarea'?undefined:type,value:value??''}));
const select=(name,label,values,value='')=>el('label',{},label,el('select',{name},values.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x.replaceAll('_',' ')];return el('option',{value:v,selected:v===value},t);} )));
const check=(name,label,value=false)=>el('label',{class:'check'},el('input',{type:'checkbox',name,checked:value===true}),label);
const values=f=>{const d=Object.fromEntries(new FormData(f));for(const c of f.querySelectorAll('input[type=checkbox]'))d[c.name]=c.checked;return d;};
const stamp=t=>t?new Date(t).toLocaleString():'Not yet';
const title=(eyebrow,t,body='')=>{main.replaceChildren(el('div',{class:'eyebrow'},eyebrow),el('h1',{},t),el('p',{class:'intro'},body));};
function modal(t,...nodes){dialog.replaceChildren(el('div',{class:'row spread'},el('h2',{},t),btn('Close',()=>dialog.close(),'quiet')),...nodes);if(!dialog.open)dialog.showModal();}
async function api(action,data,publicCall=false){const prefix=ownerMode&&!publicCall?'site-management/live/':'portal/';const r=await fetch('/api/addon/'+prefix+action,{method:data===undefined?'GET':'POST',headers:{...(token?{Authorization:'Bearer '+token}:{}),...(data===undefined?{}:{'Content-Type':'application/json','X-Rich-Row-Request':'1'})},body:data===undefined?undefined:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw Error(b.error||'Unable to complete this action.');return b;}
async function auth(path,data){const captcha=data.captchaToken||await botCheck(authConfig?.turnstileSiteKey,'account');delete data.captchaToken;if(captcha)data={...data,gotrue_meta_security:{captcha_token:captcha}};const r=await fetch(authConfig.supabaseUrl+'/auth/v1/'+path,{method:'POST',headers:{apikey:authConfig.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||d.message||'Sign-in could not be completed.');return d;}
function login(){const role=q.get('watch')||q.get('guest')==='1'?'customer':'artist';if(!authConfig?.supabaseUrl){say('Account sign-in is not connected.');return;}openSignIn({site,role,name:brands[site][0],authenticate:d=>auth('token?grant_type=password',d),resend:d=>auth('resend?redirect_to='+encodeURIComponent(location.origin+'/account.html?site='+site+'&role='+role+'&verified=1'),{...d,type:'signup'}),signup:d=>auth('signup?redirect_to='+encodeURIComponent(location.origin+'/account.html?site='+site+'&role='+role+'&verified=1'),{...d,data:{requested_site:site,requested_role:role}}),recover:d=>auth('recover?redirect_to='+encodeURIComponent(location.origin+'/account.html?site='+site+'&role='+role+'&recovery=1'),{email:d.email,captchaToken:d.captchaToken}),onSuccess:async s=>{if(!s.access_token)throw Error('Sign-in did not return an account session.');token=s.access_token;sessionStorage.setItem('rr_artist_token',token);const u=new URL(location.href);u.searchParams.delete('signin');history.replaceState(null,'',u);await load();if(q.get('guest')==='1')openInvitedGuest();}});}
async function load(){document.querySelector('#site-name').textContent=brands[site][0];document.querySelector('#public-site').href=brands[site][1];document.querySelector('#account').replaceChildren(ownerMode?link('My account','/account.html'):token?btn('Sign out',async()=>{await cleanup();clearSession();token='';await load();},'quiet'):btn('Sign in',login,'quiet'));config=await api('config?site='+site,undefined,true);if((token||ownerMode)&&q.get('staff')!=='1'&&!['watch','feed'].includes(tab)&&q.get('guest')!=='1'){model=await api('home?site='+site);}else model={records:[],assets:[],access:[]};renderNav();await show(tab);}
function renderNav(){const items=ownerMode?[['live','Go live'],['settings','Settings']]:admin?[['home','Overview'],['releases','Release review'],['posts','Post moderation'],['live','Live Control'],['statistics','Statistics & Revenue'],['messages','Messages'],['access','Approve artists'],['settings','Connections']]:[['home','Overview'],['profile','My profile'],['posts','My posts'],['releases','Music submissions'],['live','Go live'],['analytics','Insights'],['statistics','My Statistics'],['messages','Label messages'],['settings','Settings']];nav.replaceChildren(...items.map(([key,label])=>btn(label,()=>key==='live'&&!admin&&gate()?liveSetup():navigate(key),key===tab?'active':'')));}
async function cleanup(){liveGiftsUI?.destroy();liveGiftsUI=null;if(phoneStudio){const current=phoneStudio;phoneStudio=null;await current.dispose();}if(player){player.destroy();player=null;}clearInterval(heartbeatTimer);clearInterval(watchTimer);clearInterval(chatTimer);if(preview){preview.getTracks().forEach(t=>t.stop());preview=null;}if(room){await room.disconnect();room=null;}editing=false;}
async function navigate(next){if(editing&&!confirm('Leave this form? Save your changes first.'))return;if(room&&tab==='studio'){say('End the stream before leaving the live studio.');return;}await cleanup();tab=next;renderNav();await show(next);}
const records=k=>model.records.filter(r=>r.kind===k&&!['deleted','hidden'].includes(r.state));
function gate(){if(ownerMode)return true;if(!token){title('PRIVATE ARTIST WORKSPACE','Your next chapter starts here.','Create, submit music, connect with your label, and go live from your phone.');main.append(el('section',{class:'hero-live'},el('div',{class:'eyebrow'},brands[site][0]),el('h2',{},'One home for your music.'),el('p',{},'A private creator studio, built around your sound and your audience.'),btn('Sign in / Create account',login,'gold')),supportPanel());return false;}if(!model.access.some(a=>a.status==='active')){title('ARTIST ACCESS','Your private studio.','Artist access is reviewed by the label. Fan memberships stay separate.');main.append(el('section',{class:'panel'},el('p',{},model.access.length?'Access status: '+({active:'Approved',pending:'Waiting for approval',suspended:'Blocked',rejected:'Declined'}[model.access[0].status]||model.access[0].status):'Request access to your artist workspace.'),model.access.length?btn('Check status',load,'secondary'):btn('Request artist access',async()=>{await api('request-access',{site,display_name:brands[site][0]});await load();})));return false;}return true;}
async function show(next){if(next==='watch')return watch(q.get('watch'));if(next==='feed')return feed();if(next==='statistics'&&(ownerMode||token))return statisticsScreen();if(!gate())return;return ({home:home,profile:profile,posts:posts,releases:releases,live:liveLibrary,messages:messages,analytics:analytics,settings:settings,access:accessPanel}[next]||home)();}
function home(){if(ownerMode){liveLibrary();return;}const p=records('profile')[0]?.data||{},complete=[p.stage_name,p.bio,p.photo_id,p.social_links||p.music_links].filter(Boolean).length*25;title(admin?'LABEL ADMINISTRATION':'YOUR CREATOR STUDIO',admin?'The label, connected.':'Welcome, '+(p.stage_name||brands[site][0])+'.',admin?'Review music, support artists, and manage your four connected workspaces.':'A little progress today. A bigger stage tomorrow.');if(admin)main.append(el('section',{class:'panel'},el('h3',{},model.access.filter(a=>a.status==='pending').length+' artist approval requests'),btn('Approve artists',()=>navigate('access'),'gold')),el('div',{class:'toolbar'},...Object.entries(brands).map(([s,[name]])=>link(name,'/addons/portal?admin=1&site='+s))));main.append(el('div',{class:'grid'},metric('Releases',records('release').length,'Your music in motion'),metric('Awaiting review',records('release').filter(r=>['submitted','under_review'].includes(r.state)).length,'Keep the next step clear'),metric('Posts',records('post').filter(r=>r.state==='published').length,'Stories you have shared'),metric('Live sessions',records('stream').length,'Your broadcasts and replays')));main.append(el('div',{style:'height:24px'}));if(!admin)main.append(el('section',{class:'panel composer'},el('h3',{},'What’s on your mind?'),el('p',{class:'muted'},'Share a studio moment, a photo, or your next move.'),btn('Create a post',()=>postEditor()),btn('Photo / short video',()=>postEditor(),'secondary')));main.append(el('section',{class:'hero-live'},el('span',{class:'pill'},'FROM YOUR PHONE OR DESKTOP'),el('h2',{},'Your audience. Your moment.'),el('p',{},'Go live, share your story, and let people support your music as they watch.'),btn(admin?'View livestreams':'Go live',()=>admin?navigate('live'):liveSetup(),'live-entry'),!admin?btn('Go live with OBS',()=>obsSetup(),'secondary'):null));main.append(el('div',{style:'height:24px'}),el('section',{class:'panel'},el('div',{class:'row spread'},el('h3',{},'Your next release'),btn(admin?'Review music':'Submit music',()=>admin?navigate('releases'):releaseEditor(),'secondary')),...records('release').slice(0,3).map(releaseCard),records('release').length?null:el('p',{class:'muted'},'Your first release starts with a draft.')));if(!admin)main.append(el('section',{class:'panel'},el('div',{class:'row spread'},el('h3',{},'Profile completion'),el('strong',{},complete+'%')),el('progress',{value:complete,max:100}),btn('Complete my profile',()=>navigate('profile'),'quiet')));for(const r of records('release').filter(r=>r.state==='changes_requested'))main.append(el('div',{class:'warning'},el('strong',{},r.data.title+' needs a correction'),el('p',{},r.data.review_note),btn('Open corrections',()=>releaseEditor(r),'secondary')));}
function metric(label,value,note){return el('div',{class:'card metric'},el('small',{},label),el('strong',{},value),el('small',{},note));}
function supportPanel(streamId){return el('section',{class:'support-panel'},el('h3',{},'Support '+brands[site][0]),el('p',{},'Enjoying the music? Show some love.'),btn('♥ Support / Donate',()=>{trackEvent('donate_click',streamId);return support(streamId);},'gold'),el('small',{},'Secure Stripe checkout · Payments received by Rich Row Records.'));}
function support(streamId){const f=el('form',{},el('p',{},'Your one-time support for '+brands[site][0]+' is paid directly to Rich Row Records through Stripe.'),el('div',{class:'toolbar'},...[5,10,25,50].map(n=>btn('$'+n,()=>f.elements.amount.value=n,'secondary'))),field('amount','Amount in USD',10,'number'),el('p',{class:'muted'},'Voluntary support, not represented as a tax-deductible charitable donation. No subscription. Your broadcast stays open.'));f.elements.amount.min=1;f.elements.amount.max=1000;f.elements.amount.step='.01';const request_id=crypto.randomUUID();f.append(el('button',{type:'submit',class:'gold',disabled:!config.support_enabled},config.support_enabled?'Continue to secure checkout':'Stripe connection needed'));f.onsubmit=async e=>{e.preventDefault();const popup=window.open('about:blank','_blank');if(popup)popup.opener=null;try{const result=await api('support',{site,amount_cents:Math.round(Number(f.elements.amount.value)*100),stream_id:streamId,request_id},true);if(popup)popup.location=result.url;else f.append(el('a',{href:result.url,target:'_blank',rel:'noopener',class:'cta'},'Open secure Stripe checkout'));}catch(err){popup?.close();say(err.message);}};modal('Show your support',f);}
async function upload(file,purpose){if(!file)throw Error('Choose a file first.');const limit=purpose==='master'?256:40;if(file.size>limit*1024*1024)throw Error('This upload supports files up to '+limit+' MB.');say('Uploading '+file.name+'…');const r=await fetch('/api/addon/'+(ownerMode?'admin/':'')+'portal/upload?site='+site+'&purpose='+purpose,{method:'POST',headers:{...(!ownerMode?{Authorization:'Bearer '+token}:{}),'X-Rich-Row-Request':'1','X-File-Name':encodeURIComponent(file.name),'Content-Type':'application/octet-stream'},body:file});const b=await r.json();if(!r.ok)throw Error(b.error);model.assets.unshift(b);say('Saved and checked: '+file.name);return b;}
function uploadControl(label,purpose,current,done){const accept={master:'.wav',artwork:'.jpg,.jpeg,.png',photo:'.jpg,.jpeg,.png',video:'.mp4',document:'.pdf,.txt'}[purpose],input=el('input',{type:'file',accept}),note=el('span',{class:'file-label'},model.assets.find(a=>a.id===current)?.name||'No file selected');const wrap=el('label',{},label,input,note);input.onchange=async()=>{input.disabled=true;try{const a=await upload(input.files[0],purpose);note.textContent=a.name;done(a.id);}catch(e){say(e.message);}finally{input.disabled=false;}};return wrap;}
function profile(){const prior=records('profile')[0],d=structuredClone(prior?.data||{});title('ARTIST IDENTITY','Make it yours.','Your account details are private. Publishing to your public website remains a label-managed action.');const f=el('form',{class:'panel'},field('stage_name','Artist / stage name',d.stage_name||brands[site][0]),field('bio','Biography',d.bio,'textarea'),uploadControl('Profile photo','photo',d.photo_id,id=>d.photo_id=id),uploadControl('Artist logo','photo',d.logo_id,id=>d.logo_id=id),field('social_links','Social links — one HTTPS address per line',d.social_links,'textarea'),field('music_links','Music-platform links — one HTTPS address per line',d.music_links,'textarea'));f.append(el('button',{type:'submit'},'Save profile'));f.onsubmit=async e=>{e.preventDefault();try{await api('save',{site,kind:'profile',id:prior?.id,revision:prior?.revision,data:{...d,...values(f)}});say('Profile saved.');model=await api('home?site='+site);profile();}catch(err){say(err.message);}};main.append(f);}
function posts(){title(admin?'CONTENT REVIEW':'YOUR STORIES',admin?'Post moderation.':'Stay in the conversation.','Text, photos, and short videos—with audience controls.');if(!admin)main.append(btn('Create post',()=>postEditor()));const list=records('post');if(!list.length)main.append(el('p',{class:'empty'},'No posts yet. Your next update belongs here.'));for(const r of list){const card=el('article',{class:'card'},el('div',{class:'row spread'},el('span',{class:'pill'},r.state+' · '+r.audience),el('small',{class:'muted'},stamp(r.updated_at))),el('p',{class:'post-body'},r.data.body),btn(admin?'Hide post':'Edit post',async()=>{if(admin){await api('moderate',{id:r.id,action:'hide'});await load();}else postEditor(r);},'secondary'),btn('Delete',async()=>{if(!confirm('Remove this post from your feed?'))return;await api('moderate',{id:r.id,action:'delete'});await load();},'quiet'));if(r.data.asset_id)card.append(btn('View attachment',()=>previewAsset(r.data.asset_id),'quiet'));main.append(card);}}
function postEditor(r){const d=structuredClone(r?.data||{}),f=el('form',{},field('body','What’s on your mind?',d.body||'','textarea'),select('audience','Who can see it?',[['private','Private · you and label admins'],['label_only','Label team only'],['public','Public']],r?.audience||'private'),uploadControl('Add photo','photo',d.asset_id,id=>d.asset_id=id),uploadControl('Or add short MP4 video','video',d.asset_id,id=>d.asset_id=id));const save=async publish=>{await api('save',{site,kind:'post',id:r?.id,revision:r?.revision,data:{...d,body:f.elements.body.value},audience:f.elements.audience.value,publish});dialog.close();model=await api('home?site='+site);tab='posts';renderNav();posts();say(publish?'Post published in your portal feed.':'Draft saved.');};f.append(btn('Save draft',()=>save(false),'secondary'),btn('Publish post',()=>save(true)));modal(r?'Edit post':'What’s on your mind?',f);}
async function previewAsset(id){const a=await api('asset?id='+id);modal(a.name,a.mime.startsWith('image/')?el('img',{src:a.url,alt:a.name,style:'max-width:100%'}):a.mime.startsWith('audio/')||a.mime.startsWith('video/')?el(a.mime.startsWith('audio/')?'audio':'video',{src:a.url,controls:true,style:'width:100%'}):el('p',{},'Private attachment'),el('a',{href:a.url,target:'_blank',rel:'noopener',class:'cta'},'Open / download file'));}
function releases(){title(admin?'DISTRIBUTION REVIEW':'YOUR CATALOG',admin?'From master to release.':'Your music, moving forward.','Draft, submit, correct, and track every release. Label approval always comes before distribution.');if(!admin)main.append(btn('+ New release',()=>releaseEditor()));const filter=select('status','Filter by status',['all','draft','submitted','under_review','changes_requested','approved','scheduled','delivered','live','rejected','cancelled'],'all'),list=el('div');main.append(filter,list);const draw=()=>{const rows=records('release').filter(r=>filter.querySelector('select').value==='all'||r.state===filter.querySelector('select').value);list.replaceChildren(...rows.map(releaseCard));if(!rows.length)list.append(el('p',{class:'empty'},'No releases in this view.'));};filter.onchange=draw;draw();}
function releaseCard(r){return el('article',{class:'card'},el('div',{class:'row spread'},el('div',{},el('span',{class:'pill'},r.state.replaceAll('_',' ')),el('h3',{},r.data.title||'Untitled release'),el('p',{class:'muted'},(r.data.tracks?.length||0)+' tracks · Requested: '+(r.data.requested_release_date||'Choose a date'))),btn(admin?'Review':(['draft','changes_requested'].includes(r.state)?'Continue draft':'View release'),()=>!admin&&['draft','changes_requested'].includes(r.state)?releaseEditor(r):releaseDetail(r),'secondary')));}
const releaseFields=[['title','Release title'],['version_title','Version / subtitle'],['primary_artist','Primary artist'],['featured_artists','Featured artists'],['label_name','Label name'],['catalog_number','Catalog number (optional)'],['upc','UPC (optional)'],['requested_release_date','Requested release date','date'],['original_release_date','Original release date (if previously released)','date'],['genre','Primary genre'],['secondary_genre','Secondary genre'],['language','Language'],['territory_codes','Territories / country codes'],['requested_dsps','Requested DSPs'],['c_owner','C-line copyright owner'],['c_year','C-line year','number'],['p_owner','P-line sound-recording owner'],['p_year','P-line year','number'],['master_rights_owner','Master rights owner'],['publishing_rights_owner','Publishing rights owner']];
const trackFields=[['title','Track title'],['primary_artist','Primary artist'],['featured_artists','Featured artists'],['additional_performers','Additional performers'],['composer','Composer full legal name'],['lyricist','Lyricist full legal name'],['producer','Producer'],['performer_credits','Performer credits'],['mixing_engineer','Mixing engineer'],['mastering_engineer','Mastering engineer'],['arranger','Arranger'],['publisher','Publisher / self-published owner'],['pro','PRO (optional)'],['ipi_cae','IPI / CAE (optional)'],['isrc','ISRC (optional)'],['iswc','ISWC (optional)'],['language','Lyrics language'],['bpm','BPM (optional)','number'],['musical_key','Musical key (optional)'],['genre','Genre'],['subgenre','Subgenre']];
const confirmationLabels={master_rights:'I own or control all necessary master rights.',contributors:'I have permission from all artists, producers, songwriters, publishers and contributors.',clearances:'Samples, interpolations, beats, loops and third-party material are cleared.',metadata:'I understand false or incomplete metadata can delay or prevent distribution.',quality:'I understand the label may reject releases for quality, rights, artwork or metadata issues.',label_review:'I understand the label must review and approve this release.',no_auto_delivery:'I understand this does not automatically send music to Labelcaster or any DSP.',agreement:'I agree to the label’s distribution agreement and terms.',artwork_rights:'I own or have permission to use the artwork.',splits_documented:'All collaborator splits and approvals are documented.',final_master:'These are final masters: no demos, rough mixes, added silence padding, unintended cutoffs or excessive distortion.'};
function releaseEditor(prior){editing=true;let d=structuredClone(prior?.data||{title:'',primary_artist:brands[site][0],label_name:'Rich Row Records',release_type:'single',territory_mode:'worldwide',dsp_mode:'all',tracks:[],confirmations:{}}),id=prior?.id,revision=prior?.revision,step=0;title('RELEASE SUBMISSION',prior?'Keep your release moving.':'Let’s build your next release.','Save your draft at any time. Only final stereo WAV masters are accepted.');const steps=el('div',{class:'steps'}),body=el('div'),footer=el('div',{class:'toolbar'});main.append(steps,body,footer);let collect=()=>{};
 const save=async()=>{collect();const r=await api('save',{site,kind:'release',id,revision,data:d});id=r.id;revision=r.revision;d=r.data;say('Draft saved at '+new Date().toLocaleTimeString());return r;};
 const draw=()=>{steps.replaceChildren(...['Release details','Cover art','Tracks & credits','Rights & review'].map((label,i)=>btn((i+1)+'. '+label,()=>{collect();step=i;draw();},i===step?'active':'secondary')));body.replaceChildren();collect=()=>{};
 if(step===0){const f=el('form',{class:'panel'},el('div',{class:'fields'},...releaseFields.map(([k,l,t])=>field(k,l,d[k]||'',t||'text'))),select('release_type','Release type',['single','ep','album','compilation','mixtape','other'],d.release_type),check('previously_released','This has been released before',d.previously_released),select('territory_mode','Territory availability',['worldwide','include','exclude'],d.territory_mode),select('dsp_mode','DSP selection',['all','selected'],d.dsp_mode),field('description','Release description / marketing notes',d.description||'','textarea'),field('marketing_plan','Artist marketing plan',d.marketing_plan||'','textarea'),field('presave_notes','Pre-save / smart-link notes',d.presave_notes||'','textarea'),field('artist_notes','Notes for label staff',d.artist_notes||'','textarea'));body.append(f);collect=()=>Object.assign(d,values(f));}
 if(step===1){const f=el('form',{class:'panel'},el('h2',{},'Artwork that represents your sound.'),el('p',{},'Square JPEG or PNG, at least 3000 × 3000 pixels. Maximum 40 MB. Unlicensed logos, trademarks, misleading branding or copyrighted material may be rejected.'),uploadControl('Cover artwork','artwork',d.artwork_id,x=>d.artwork_id=x),field('artwork_title','Artwork title',d.artwork_title||''),field('designer_credit','Designer credit',d.designer_credit||''));body.append(f);collect=()=>Object.assign(d,values(f));}
 if(step===2){body.append(el('div',{class:'warning'},'Accepted: stereo PCM WAV at 44.1 kHz / 16-bit or 24-bit; 48 kHz / 24-bit; 96 kHz / 24-bit. 48 kHz / 16-bit is rejected. Maximum 256 MB per master in this version.'));d.tracks.forEach((t,i)=>body.append(el('article',{class:'card'},el('h3',{},(i+1)+'. '+(t.title||'Untitled track')),el('p',{class:'muted'},model.assets.find(a=>a.id===t.master_id)?.name||'Master needed'),btn('Edit track & credits',()=>trackEditor(t,x=>{d.tracks[i]=x;draw();}),'secondary'),btn('Move up',()=>{if(i){[d.tracks[i-1],d.tracks[i]]=[t,d.tracks[i-1]];draw();}},'quiet'),btn('Remove',()=>{d.tracks.splice(i,1);draw();},'quiet'))));body.append(btn('+ Add track',()=>trackEditor({primary_artist:d.primary_artist,genre:d.genre,language:d.language,version:'original',vocal_type:'vocal',advisory:'not_explicit',writer_splits:[],publisher_splits:[],document_ids:[]},x=>{d.tracks.push(x);draw();}),'secondary'));}
 if(step===3){const f=el('form',{class:'panel'},el('h2',{},d.title||'Your release'),el('p',{},d.tracks.length+' tracks · '+(d.requested_release_date||'Release date needed')),config.agreement_url?el('a',{href:config.agreement_url,target:'_blank',rel:'noopener'},'Read the distribution agreement · '+config.agreement_version):el('p',{class:'warning'},'The label’s distribution agreement must be connected before final submissions open.'),...Object.entries(confirmationLabels).map(([k,l])=>check(k,l,d.confirmations?.[k])));body.append(f);collect=()=>d.confirmations=values(f);body.append(btn('Save & submit for label review',async()=>{await save();const r=await api('transition',{id,revision,state:'submitted'});editing=false;model=await api('home?site='+site);releaseDetail(r);say('Release submitted. Nothing has been sent to Labelcaster or DSPs.');},'gold'));}
 footer.replaceChildren(...[btn('Save draft',save,'secondary'),step>0?btn('Back',()=>{collect();step--;draw();},'quiet'):null,step<3?btn('Continue',()=>{collect();step++;draw();}):null].filter(Boolean));};draw();}
function trackEditor(original,done){const d=structuredClone(original),f=el('form',{},el('div',{class:'fields'},...trackFields.map(([k,l,t])=>field(k,l,d[k]||'',t||'text'))),select('version','Track version',['original','clean','explicit','radio_edit','remix','acoustic','instrumental','live','remastered','other'],d.version),select('vocal_type','Vocal or instrumental',['vocal','instrumental'],d.vocal_type),select('advisory','Content advisory',['not_explicit','clean','explicit'],d.advisory),uploadControl('Final WAV master','master',d.master_id,id=>d.master_id=id),field('writer_lines','Writer splits: one legal name | percentage per line',(d.writer_splits||[]).map(r=>r.name+' | '+r.share).join('\n'),'textarea'),field('publisher_lines','Publisher splits: one owner | percentage per line',(d.publisher_splits||[]).map(r=>r.name+' | '+r.share).join('\n'),'textarea'),field('lyrics','Lyrics (optional)',d.lyrics||'','textarea'),check('samples','Contains samples, interpolations or licensed beats',d.samples),field('sample_details','Sample / interpolation / beat-license details',d.sample_details||'','textarea'),uploadControl('Attach license, split sheet or collaborator agreement','document',null,id=>{d.document_ids=d.document_ids||[];d.document_ids.push(id);}));f.append(el('p',{class:'muted'},'Writer and publisher pools each total 100%. PRO and IPI/CAE are optional.'),btn('Save track',()=>{const v=values(f);const shares=s=>s.split('\n').filter(x=>x.trim()).map(line=>{const [name,share]=line.split('|');return {name:name?.trim(),share:Number(share)};});Object.assign(d,v,{writer_splits:shares(v.writer_lines),publisher_splits:shares(v.publisher_lines)});delete d.writer_lines;delete d.publisher_lines;done(d);dialog.close();}));modal('Track metadata & credits',f);}
function download(data,name,type='application/json'){const u=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}));const a=el('a',{href:u,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function csv(rows){return rows.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');}
function releaseDetail(r){editing=false;title(r.state.replaceAll('_',' '),r.data.title||'Release details','Revision '+r.revision+' · Requested '+r.data.requested_release_date);main.append(el('section',{class:'panel'},el('h3',{},'Release summary'),el('p',{},r.data.primary_artist+' · '+r.data.label_name+' · '+r.data.release_type),el('p',{},r.data.genre+' / '+r.data.language),r.data.review_note?el('div',{class:'warning'},r.data.review_note):null,...(r.data.tracks||[]).map((t,i)=>el('div',{class:'card'},el('h3',{},(i+1)+'. '+t.title),el('p',{},t.primary_artist+' · '+t.advisory),btn('Listen / download master',()=>previewAsset(t.master_id),'secondary'))),r.data.artwork_id?btn('Inspect artwork',()=>previewAsset(r.data.artwork_id),'secondary'):null));main.append(btn('View submission history',async()=>{const rows=await api('history?id='+r.id);modal('Revision history',...rows.map(x=>el('div',{class:'card'},el('strong',{},'Revision '+x.revision+' · '+x.state),el('p',{},stamp(x.created_at)))));},'quiet'));if(admin){const form=el('form',{class:'panel'},el('h2',{},'Label decision'),field('reason','Artist-facing review note','','textarea'));const options={submitted:['under_review'],under_review:['changes_requested','approved','rejected'],approved:['scheduled','delivered','changes_requested'],scheduled:['delivered','changes_requested'],delivered:['live']}[r.state]||[];for(const state of options)form.append(btn(state.replaceAll('_',' '),async()=>{let distribution={};if(['scheduled','delivered','live'].includes(state)){return distributionDialog(r,state);}const next=await api('transition',{id:r.id,revision:r.revision,state,reason:form.elements.reason.value,distribution});model=await api('home?site='+site);releaseDetail(next);}));main.append(form);if(r.data.approval){main.append(el('section',{class:'panel'},el('h3',{},'Manual Labelcaster handoff'),el('p',{},'This is an entry packet, not an API submission. Keep composition splits separate from master-revenue contracts.'),btn('Export complete metadata JSON',()=>download({format:'rich-row-portal-v1',release_id:r.id,revision:r.revision,metadata:r.data,delivery:'manual'},'release-'+r.id+'.json'),'secondary'),btn('Export tracks CSV',()=>download(csv([['Track','Title','Primary artist','ISRC','Composer','Lyricist','Publisher'],...r.data.tracks.map((t,i)=>[i+1,t.title,t.primary_artist,t.isrc,t.composer,t.lyricist,t.publisher])]),'tracks.csv','text/csv'),'secondary'),btn('Print summary / Save PDF',()=>window.print(),'secondary')));}}}
function distributionDialog(r,state){const d=r.data.distribution||{},f=el('form',{},field('partner_id','Labelcaster release ID',d.partner_id||''),field('upc','Assigned UPC',d.upc||''),field('confirmed_date','Confirmed release date',d.confirmed_date||'','date'),field('delivery_date','Delivery date',d.delivery_date||'','date'),field('isrcs','Assigned ISRCs — track number and code',d.isrcs||'','textarea'),field('dsp_links','Verified DSP links — one per line',d.dsp_links||'','textarea'));f.append(btn('Record '+state,async()=>{const next=await api('transition',{id:r.id,revision:r.revision,state,distribution:values(f)});dialog.close();model=await api('home?site='+site);releaseDetail(next);}));modal('Manual distribution update',f);}
async function liveLibrary(){
 title(admin?'CONSOLE / LIVE CONTROL':'LIVE STUDIO',admin?'Live Control':'I’m live. Tap in.',admin?'Control live sessions across all four sites. Feature a session on Rich Row, end a broadcast, and download session records.':'Go live with your camera and microphone, or connect OBS or a mobile streaming app. Your title and description are optional.');
 main.append(el('p',{class:config.live_enabled?'pill':'warning'},config.live_enabled?'Live video is connected.':'Live video is temporarily unavailable. Please check the studio connection.'));
 if(config.browser_live?.enabled)main.append(el('p',{class:'muted'},'Each event lasts up to seven hours from its first live video. Reconnecting does not reset the clock. '+(config.browser_live.max_streams===1?(config.group_live?.enabled?'One shared broadcast, with you and up to 3 guests.':'One phone broadcast can run at a time across the four sites.'):'Up to '+config.browser_live.max_streams+' phone broadcasts can run at once across the four sites.')));
 main.append(el('p',{class:'muted'},'Server recording is off. To keep a recording, use local recording in OBS or your streaming app.'));
 if(!admin)main.append(btn('Go live',()=>liveSetup(),'live-entry'),btn('Go live with OBS',()=>obsSetup(),'secondary'));
 main.append(btn('Refresh live status',()=>liveLibrary(),'secondary'));
 const sessions=admin?await api('live-control'):records('stream');
 for(const r of sessions){const active=['live','preparing'].includes(r.state);main.append(el('article',{class:'card'},el('span',{class:'pill'},(brands[r.site]?.[0]||r.site)+' · '+r.state),el('h3',{},r.data.title),el('p',{class:'muted'},r.data.description||'No description'),el('div',{class:'toolbar'},!admin&&(['scheduled','failed','preparing','live'].includes(r.state)||r.event?.open&&r.state==='ended')?btn(r.state==='ended'?'Reconnect this live':'Open live studio',()=>liveSetup(r),'live-entry'):null,(['scheduled','failed','preparing','live'].includes(r.state)||r.event?.open)?btn('Open OBS setup',()=>studio(r),'secondary'):null,link('Viewer screen','/addons/portal?site='+r.site+'&watch='+r.id),btn('Recordings & session record',()=>recordingsDialog(r),'secondary'),btn('Live revenue',()=>liveRevenueDialog(r),'secondary'),r.event?.open?btn('Continue with these passes',()=>continuationDialog(r),'secondary'):null,r.event?el('small',{},eventLabel(r.event)):null,admin&&active?btn('End live',async()=>{await api('end',{id:r.id});say('End requested. The provider may take a few seconds to stop playback.');await liveLibrary();},'danger'):null,btn('Ticket access',()=>pricingDialog(r),'gold'),admin&&r.audience==='public'?btn(r.data.featured_on_richrow?'Remove from Rich Row homepage':'Show on Rich Row homepage',async()=>{await api('feature',{id:r.id,featured:!r.data.featured_on_richrow});await liveLibrary();},'secondary'):null)));}
 if(!sessions.length)main.append(el('p',{class:'empty'},'Live sessions will appear here.'));
}
function liveSetup(record=null){phoneStudio=openPhoneStudio({record,site,config,api,onClose:()=>{phoneStudio=null;void load();}});}
async function obsSetup(){const f=el('form',{},field('title','Title (optional)','I’m live. Tap in.'),select('audience','Who can watch?',[['public','Public · your website'],['private','Private · connection test']],'public'),el('p',{},'Preparing OBS does not start your broadcast. You start it in OBS.'));f.append(btn('Set up OBS',async()=>{const r=await api('stream',{site,...values(f)});dialog.close();await studio(r);},'gold'));const existing=model.records.filter(r=>r.kind==='stream'&&r.site===site&&(['scheduled','failed','preparing','live'].includes(r.state)||r.state==='ended'&&r.event?.open)).slice(0,12);modal('Go live with OBS',...existing.map(r=>btn('Open existing event: '+r.data.title,async()=>{dialog.close();await studio(r);},'secondary')),f);}
async function studio(r){
 await cleanup();tab='studio';renderNav();title('OBS LIVE STUDIO',r.data.title,'Send your OBS scene to the same website player. Your phone studio remains available.');
 const status=el('p',{class:'pill','aria-live':'polite'},'Not broadcasting'),clock=el('p',{class:'muted'}),settings=el('section',{class:'panel'}),chat=el('section',{class:'panel'});main.append(status,clock,settings);
 const privateField=(name,label,value,masked=false)=>{const n=field(name,label,value,masked?'password':'text'),input=n.querySelector('input');input.readOnly=true;input.autocomplete='off';input.spellcheck=false;return n;};
 const downloadProfile=async()=>{const file=await api('obs-profile',{id:r.id}),bytes=Uint8Array.from(atob(file.base64),x=>x.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:file.content_type})),a=el('a',{href:url,download:file.file_name});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Private OBS profile downloaded. Unzip it, then choose OBS → Profile → Import.');};
 const connect=async()=>{const result=await api('start',{id:r.id}),c=result.credentials;r=result;settings.replaceChildren(el('h2',{},'Connect OBS'),el('p',{},'In OBS: Settings → Stream → Service: Custom. Paste these two values.'),privateField('server','Server',c.serverUrl),btn('Copy server',async()=>{await navigator.clipboard.writeText(c.serverUrl);say('Server copied.');},'secondary'),privateField('streamKey','Private stream key',c.streamKey,true),btn('Copy stream key',async()=>{await navigator.clipboard.writeText(c.streamKey);say('Private stream key copied.');},'secondary'),el('p',{class:'muted'},'This key belongs only to this event. Keep it private.'),btn('Download OBS profile',downloadProfile,'gold'),btn('Refresh connection key',connect,'quiet'));await update();};
 const update=async()=>{try{const s=await api('watch?id='+r.id);status.textContent=s.state==='live'?'● LIVE · video received':s.event?.open===false?'Event finished':s.event?'Reconnecting · restart streaming in OBS':s.state==='scheduled'?'Prepare your OBS connection below':'Ready · click Start Streaming in OBS';status.classList.toggle('obs-live-active',s.state==='live');clock.textContent=s.event?eventLabel(s.event):'Up to 7 hours. The event clock starts when your video arrives.';}catch{status.textContent='Checking the connection… Keep OBS open.';}};
 settings.append(el('h2',{},'Your private OBS connection'),btn('Prepare OBS connection',connect,'gold'));
 main.append(el('section',{class:'panel'},el('h2',{},'Three steps to go live'),el('ol',{},el('li',{},'Copy the server and key above into OBS, or download and import the OBS profile.'),el('li',{},'Choose your scene. Check that your camera looks right and the audio meter moves.'),el('li',{},'Click Start Streaming in OBS. This page shows LIVE when video reaches the server.')),el('details',{},el('summary',{},'Recommended OBS settings'),el('p',{},'Video: 1280 × 720, 30 FPS, H.264, CBR 2,500 kbps, keyframes every 2 seconds. Audio: AAC, 160 kbps, 48 kHz stereo, track 1. Automatic reconnect: on.')),el('p',{},'Stop Streaming in OBS pauses this event. Start Streaming again to reconnect using the same pass and original deadline. Use End event below only when you are finished.'),el('p',{class:'muted'},'OBS broadcasts the scene you build in OBS. To accept and mix website guest cameras, use the phone/browser studio.')));
 main.append(el('section',{class:'panel'},el('h2',{},'Use your phone instead'),el('p',{},'Stop OBS first, then open the phone studio for this same event.'),btn('Open phone studio',()=>liveSetup(r),'secondary')));
 if(r.audience==='public')main.append(liveShareButton({host:true,getRecord:()=>api('watch?id='+r.id),onNotice:say}));
 main.append(link('Open viewer screen','/addons/portal?site='+r.site+'&watch='+r.id),btn('Ticket access',()=>pricingDialog(r),'secondary'),btn('Live revenue',()=>liveRevenueDialog(r),'secondary'),btn('End event',async()=>{if(!confirm('Finish this event permanently? Viewers’ passes will expire. To reconnect later, only stop streaming in OBS.'))return;await api('end',{id:r.id});await cleanup();tab='live';await load();},'danger'),chat);
 watchTimer=setInterval(update,5000);await update();await renderChat(chat,r.id,true);
}
async function recordingsDialog(r){const d=await api('recordings?id='+r.id);modal('Recordings & session record',el('p',{class:'warning'},d.note),...d.videos.map(v=>el('article',{class:'card'},el('h3',{},v.title||r.data.title),el('p',{},stamp(v.created_at)),v.mp4?el('a',{href:v.mp4,target:'_blank',rel:'noopener',download:'live-recording.mp4',class:'cta gold'},'Download recording'):el('p',{},'Recording is still processing.'))),!d.videos.length?el('p',{},'No server recording is available. Your session record can still be downloaded below.'):null,btn('Download session record',()=>download({...d.record,recordings:d.videos.map(v=>({id:v.id,created_at:v.created_at})),exported_at:new Date().toISOString()},'live-session-'+r.id+'.json'),'secondary'),btn('Download readable record',()=>download(Object.entries(d.record).map(([k,v])=>k.replaceAll('_',' ')+': '+(v??'Not yet')).join('\n'),'live-session-'+r.id+'.txt','text/plain'),'secondary'));}
async function renderChat(container,id,manage=false){const list=el('div',{class:'chat-box'}),f=el('form',{},field('body','Message','','text'));container.replaceChildren(el('h3',{},'Live chat'),list);const draw=async()=>{try{const rows=await api('chat?id='+id);list.replaceChildren(...rows.reverse().map(m=>el('div',{class:'chat-line'},el('strong',{},m.name),el('span',{},m.body),manage?btn('Remove',async()=>{await api('moderate',{id,action:'delete_chat',chat_id:m.id});await draw();},'quiet'):null,manage?btn('Block',async()=>{await api('moderate',{id,action:'block',user_id:m.user_id});await draw();},'quiet'):null)));if(!rows.length)list.append(el('p',{class:'muted'},'Say hello. Keep it respectful.'));}catch(e){list.textContent=e.message;}};if(token||ownerMode){f.elements.body.maxLength=500;f.append(el('button',{type:'submit'},'Send'));f.onsubmit=async e=>{e.preventDefault();try{await api('chat',{id,body:f.elements.body.value});f.reset();await draw();}catch(err){say(err.message);}};container.append(f);}else container.append(btn('Sign in to chat',login,'secondary'));await draw();chatTimer=setInterval(draw,5000);}
async function watch(id){await cleanup();title('LIVE & REPLAY','Loading broadcast…');if(token&&q.get('ticket')){await api('ticket',{id:q.get('ticket')});q.delete('ticket');}const s=await api('watch?id='+id,undefined,!ownerMode);if(s.site!==site){location.replace(brands[s.site][1]+'/live.html?watch='+id);return;}if(s.continuation_id){location.replace('/addons/portal?site='+s.site+'&watch='+s.continuation_id);return;}config=s.config;title(s.state==='live'?'LIVE NOW':'BROADCAST & REPLAY',s.title,s.description);if(s.event)main.append(el('p',{class:'pill'},eventLabel(s.event)));if(s.audience==='public'&&['live','preparing','scheduled'].includes(s.state)){const share=liveShareButton({record:s,getRecord:()=>api('watch?id='+id,undefined,!ownerMode),onNotice:say});main.append(share);if(q.get('share')==='1'){q.delete('share');share.click();}}const stage=el('div',{class:'video-stage'}),chat=el('div',{class:'panel'});main.append(el('div',{class:'live-grid'},el('section',{},stage,supportPanel(id),el('p',{class:'muted'},'Support checkout opens separately so you can keep watching.')),chat));let playing=false,session;const pulse=async()=>{if(!playing||document.hidden)return;try{const b=await api('heartbeat',{id,session},true);session=b.session;}catch{}};
 if(s.locked){renderPaywall(stage,s,id);}
 else if(s.credentials?.provider==='mediamtx'){player=await mountMediaPlayer(stage,{url:s.credentials.hlsUrl,title:s.title,refresh:()=>api('watch?id='+id,undefined,!ownerMode),onPlaying:v=>{playing=v;if(v)pulse();},onMessage:say,onContinuation:next=>location.replace('/addons/portal?site='+site+'&watch='+next)});}
 else if(s.credentials){room=new window.LivekitClient.Room({adaptiveStream:true});room.on(window.LivekitClient.RoomEvent.TrackSubscribed,track=>{const media=track.attach();media.playsInline=true;media.controls=track.kind==='video';stage.append(media);media.onplaying=()=>playing=true;media.onpause=()=>playing=false;});await room.connect(s.credentials.url,s.credentials.token);stage.append(btn('Tap to enable sound',async()=>{await room.startAudio();},'secondary'));room.on(window.LivekitClient.RoomEvent.Disconnected,()=>{playing=false;say('This live connection ended. Refresh for the replay.');});}
 else if(s.replay_url){const v=el('video',{src:s.replay_url,controls:true,playsInline:true});v.onplaying=()=>playing=true;v.onpause=()=>playing=false;stage.append(v);}else stage.append(el('p',{style:'padding:24px'},s.state==='scheduled'?'This live has not started yet.':s.recording_state==='processing'?'Your replay is processing.':s.recording_state==='ready'?'This replay has not been published.':'The artist is not live right now.'),btn('Refresh',()=>watch(id),'secondary'));
 if(s.state==='live'&&!s.locked&&!s.can_manage&&config.group_live?.enabled)main.append(btn('Request to join',()=>{if(!token){login();return;}player?.destroy();player=null;playing=false;phoneStudio=openGuestStudio({api,recordId:id,onClose:()=>{phoneStudio=null;void watch(id);}});},'live-entry'));
 if(s.state==='live'&&!s.locked){const giftPanel=el('div');main.append(giftPanel);liveGiftsUI=mountLiveGifts({stage,container:giftPanel,api,id,site,signedIn:!!token||ownerMode,onSignIn:login});}
 heartbeatTimer=setInterval(pulse,15000);if(!s.credentials&&!s.locked&&s.event?.open)watchTimer=setInterval(async()=>{try{const next=await api('watch?id='+id,undefined,!ownerMode);if(next.state==='live'||next.continuation_id||!next.event?.open)await watch(id);}catch{}},5000);await renderChat(chat,id,s.can_manage);}
function replayEditor(r){const f=el('form',{},field('title','Replay title',r.data.title),field('description','Replay description',r.data.description,'textarea'),select('audience','Replay visibility',['private','label_only','public'],r.audience),check('published','Publish replay for this audience',r.data.replay_published),el('p',{class:'warning'},'Download important videos and keep your own backup. Stored recordings are subject to the label’s storage policy.'));f.append(btn('Save replay',async()=>{await api('replay',{id:r.id,...values(f)});dialog.close();model=await api('home?site='+site);liveLibrary();}),btn('Download my recording',async()=>{const d=await api('replay',{id:r.id,download:true});window.open(d.url,'_blank','noopener');},'secondary'),btn('Check recording status',async()=>{const s=await api('watch?id='+r.id);say('Recording: '+s.recording_state);},'quiet'));modal('Replay & recording',f);}
async function streamAnalytics(r){const a=await api('analytics?id='+r.id);modal(r.data.title+' · analytics',el('div',{class:'grid'},metric('Viewing sessions',a.sessions,'At least 10 seconds'),metric('Unique viewers',a.unique_viewers,'Anonymous counts are estimates'),metric('Minutes watched',(a.watch_seconds/60).toFixed(1),'Playing time'),metric('Average watch',a.average_seconds===null?'—':Math.round(a.average_seconds)+'s','Per qualified session')),el('p',{class:'muted'},a.note),btn('Download CSV',()=>download(csv([['Metric','Value'],...Object.entries(a).filter(([k,v])=>typeof v==='number').map(([k,v])=>[k,v])]),'live-analytics.csv','text/csv'),'secondary'));}
function analytics(){title('ARTIST INSIGHTS','Progress, at your pace.','Your own activity comes first. Audience size is not a measure of your worth.');main.append(el('div',{class:'grid'},metric('Posts published',records('post').filter(r=>r.state==='published').length,'All time'),metric('Live sessions',records('stream').length,'All time'),metric('Releases submitted',records('release').filter(r=>r.state!=='draft').length,'All time'),metric('Approved releases',records('release').filter(r=>r.data.approval).length,'All time')),el('p',{class:'warning'},'Advanced growth scores, retention timelines and date-range reports need additional analytics processing. No estimated or invented scores are shown.'));for(const r of records('stream'))main.append(btn(r.data.title+' — View analytics',()=>streamAnalytics(r),'secondary'));}
function messages(){title('LABEL CONNECTION','Keep the conversation moving.','Questions, feedback, and release corrections in one private place.');if(admin){const owners=[...new Set(model.access.map(a=>a.owner_id))];const choose=select('owner_id','Artist account',owners.map(id=>[id,model.access.find(a=>a.owner_id===id)?.display_name+' · '+id.slice(0,8)]));main.append(choose);const f=el('form',{class:'panel'},field('body','Message to artist','','textarea'));f.append(btn('Send to artist',async()=>{await api('save',{site,kind:'message',owner_id:choose.querySelector('select').value,data:values(f)});await load();}),btn('Save internal note',async()=>{await api('save',{site,kind:'note',owner_id:choose.querySelector('select').value,data:values(f)});await load();},'secondary'));main.append(f);}else{const f=el('form',{class:'panel'},field('body','Message to the label','','textarea'));f.append(btn('Send message',async()=>{await api('save',{site,kind:'message',data:values(f)});await load();}));main.append(f);}for(const r of model.records.filter(r=>r.kind==='message'||admin&&r.kind==='note'))main.append(el('article',{class:'card'},el('span',{class:'pill'},r.kind==='note'?'Internal · staff only':r.data.sender),el('p',{class:'post-body'},r.data.body),el('small',{class:'muted'},stamp(r.created_at))));}
function accessPanel(){title('CONSOLE / ARTIST APPROVALS','Approve once. Create freely.','Requests from all four websites appear here. Approval stays active until you block access. Each artist can manage only their own portal records and enabled site tools.');const sorted=[...model.access].sort((a,b)=>(a.status==='pending'?0:1)-(b.status==='pending'?0:1));main.append(el('div',{class:'grid'},metric('Waiting for approval',sorted.filter(a=>a.status==='pending').length,'Across all four sites'),metric('Approved artists',sorted.filter(a=>a.status==='active').length,'Ongoing access')),btn('Refresh requests',load,'secondary'),btn('Live gift benefits',giftBenefitsDialog,'gold'));for(const a of sorted){const card=el('article',{class:'card'},el('span',{class:'pill'},brands[a.site]?.[0]||a.site),el('h3',{},a.display_name),el('p',{class:'muted'},'Account ID: '+a.owner_id),el('strong',{},a.status==='active'?'Approved · ongoing access':a.status==='pending'?'Waiting for your approval':a.status==='suspended'?'Blocked':a.status==='rejected'?'Declined':a.status),el('p',{},'Private profile, posts, music uploads and previews, label messages, and mobile live tools when streaming is connected.'));const actions=el('div',{class:'toolbar'});if(a.status!=='active')actions.append(btn(a.status==='suspended'?'Unblock artist':'Approve artist',async()=>{await api('review-access',{id:a.id,site:a.site,status:'active'});say('Approved. This artist now has ongoing access to '+brands[a.site][0]+'.');await load();},'gold'));if(a.owner_id!==model.current_user_id&&a.status!=='suspended')actions.append(btn('Block portal access',async()=>{await api('review-access',{id:a.id,site:a.site,status:'suspended'});await load();},'secondary'));if(a.owner_id!==model.current_user_id&&a.status==='pending')actions.append(btn('Decline request',async()=>{await api('review-access',{id:a.id,site:a.site,status:'rejected'});await load();},'quiet'));actions.append(link('Open site workspace','/addons/portal?admin=1&site='+a.site));if(a.owner_id===model.current_user_id)card.append(el('p',{class:'pill'},'Your admin account · protected'));card.append(actions);main.append(card);}if(!sorted.length)main.append(el('section',{class:'panel'},el('h3',{},'No requests waiting.'),el('p',{},'Ask the artist to sign in on their site, then choose Request artist access. Their request will appear here.')));}
function settings(){location.assign('/settings.html');return;title('CONNECTIONS & SETTINGS','Built around your workspace.','Four public sites. Private artist accounts. One label payment account.');main.append(el('section',{class:'panel'},el('h3',{},'Payments'),el('p',{},config.support_enabled?'Stripe support checkout is connected.':'Stripe connection required.'),el('p',{},'Recipient: Rich Row Records. Support for each artist is tagged in Stripe. No new subscriptions are created.'),btn('Open support button',()=>support(),'gold')),el('section',{class:'panel'},el('h3',{},'Mobile livestreaming'),el('p',{},config.live_enabled?'MediaMTX is selected.':'MediaMTX is being connected. Live video is temporarily unavailable.'),el('p',{},'Optional title and description. Default title: I’m live. Tap in.')),el('section',{class:'panel'},el('h3',{},'Distribution agreement'),el('p',{},config.agreement_version?'Version: '+config.agreement_version:'The label must publish and configure its agreement before artists can submit.'),config.agreement_url?link('Read agreement',config.agreement_url):null),el('section',{class:'panel'},el('h3',{},'Privacy & files'),el('p',{},'Your workspace is private. Public posts and broadcasts use their selected audience. Masters, rights documents and review notes are never made public by publishing a post.')));}
async function feed(){title('LIVE, REPLAYS & UPDATES',brands[site][0]+'. Connected.','Watch the latest broadcasts, catch a replay, and support the music.');main.append(supportPanel());const rows=await api('feed?site='+site,undefined,true);if(!rows.length)main.append(el('p',{class:'empty'},'Public broadcasts and updates will appear here when the artist publishes them.'));for(const r of rows){const card=el('article',{class:'card'});if(r.kind==='stream')card.append(el('span',{class:'pill'},r.state==='live'?'LIVE NOW':'REPLAY'),el('h2',{},r.title),el('p',{},r.description),link('Watch & support','/addons/portal?site='+site+'&watch='+r.id,'cta gold'));else{card.append(el('p',{class:'post-body'},r.body));if(r.attachment)card.append(el(r.attachment.mime.startsWith('image/')?'img':'video',{src:r.attachment.url,alt:r.attachment.name,controls:true,style:'max-width:100%;max-height:500px'}));}main.append(card);}}
document.querySelector('#theme').onclick=()=>document.body.classList.toggle('dark');
window.addEventListener('beforeunload',e=>{if(editing||room){e.preventDefault();e.returnValue='';}});
async function init(){try{authConfig=await (await fetch('/api/addon/config')).json();await load();if(q.get('guest')==='1')openInvitedGuest();if((q.get('signin')==='1'||sessionStorage.getItem('rr_pending_verification'))&&!token)login();if(q.get('support')==='open'||location.pathname==='/support.html')support();if(q.get('support')==='returned')say('Thank you for supporting the music. Your payment status and receipt are confirmed by Stripe.');}catch(e){title('ARTIST PORTAL',brands[site][0],'Your studio is being connected.');main.append(el('p',{class:'warning'},e.message),admin?link('Sign in to label Console','/#/login'):btn('Sign in',login,'secondary'));}}
init();

function pricingDialog(r){const pricing=r.data.paywall||{},f=el('form',{},check('enabled','Require a paid ticket or active subscription',pricing.enabled),field('price','One-event ticket in USD',30,'number'),el('p',{},'$30 for this live event only, within its original seven-hour window. No replay, future event or recurring charge. Active subscribers on this site are included. The automatic audience threshold is awaiting its counting setting.'));f.elements.price.readOnly=true;f.elements.price.min='1';f.elements.price.max='1000';f.elements.price.step='0.01';f.append(btn('Save price & access',async()=>{if(!f.reportValidity())return;await api('pricing',{id:r.id,enabled:f.elements.enabled.checked,price_cents:Math.round(Number(f.elements.price.value)*100)});dialog.close();await liveLibrary();},'gold'));modal('Paywall & ticket price',f);}
function renderPaywall(stage,s,id){let requestId=crypto.randomUUID(),buying=false;stage.replaceChildren(el('h2',{},'Join this live'),el('p',{},'$30 · one live event, or $15/month membership'),el('p',{class:'muted'},'Your pass belongs to your signed-in account. Refreshes and reconnects do not require another purchase. Artist-approved same-day continuations keep the original event deadline. No replay or future event access.'),s.event?el('p',{},eventLabel(s.event)):null,btn(token?'Buy this live — $30':'Sign in to buy or recover access',async()=>{if(buying)return;if(!token){login();return;}buying=true;try{const result=await api('checkout',{id,request_id:requestId});if(result.access)await watch(id);else location.assign(result.url);}finally{buying=false;}},'gold'),link('Membership — $15/month',site==='richrow'?'/addons/membership':'/addons/artist-membership?site='+site),btn('I already paid · restore access',()=>watch(id),'secondary'));}
function trackEvent(kind,id){try{let visit=sessionStorage.getItem('rr_stats_visit');if(!visit){visit=crypto.randomUUID();sessionStorage.setItem('rr_stats_visit',visit);}fetch('/api/addon/portal/track',{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({site,kind,visit,stream_id:id||null}),keepalive:true}).catch(()=>{});}catch{}}
async function statisticsScreen(scope=admin?'all':site,days=30){title(admin?'CONSOLE / STATISTICS & REVENUE':'PRIVATE / MY STATISTICS',admin?'Statistics & Revenue':'My Statistics','Verified payment activity and first-party engagement, organized by website.');const filter=select('site','Website',admin?[['all','All websites'],...Object.entries(brands).map(([key,v])=>[key,v[0]])]:[[site,brands[site][0]]],scope),period=select('days','Date range',[[7,'Last 7 days'],[30,'Last 30 days'],[90,'Last 90 days']],String(days)),controls=el('div',{class:'toolbar'},filter,period);main.append(controls);controls.append(btn('Load statistics',()=>statisticsScreen(filter.querySelector('select').value,Number(period.querySelector('select').value))));const d=await api('statistics?site='+scope+'&days='+days);for(const warning of d.warnings)main.append(el('p',{class:'warning'},warning));const a=d.activity;main.append(el('div',{class:'grid'},metric('Page views',a.page_views,'Tracked visits in range'),metric('Live clicks',a.live_clicks,'Homepage watch clicks'),metric('Viewing sessions',a.viewing_sessions,'Player started'),metric('Minutes watched',(a.watch_seconds/60).toFixed(1),'Playing time estimate'),metric('Average watch',Math.round(a.average_watch_seconds)+'s','Per viewing session'),metric('Watching now',a.current_viewers,'Recent playback heartbeats'),metric('Donation clicks',a.donation_clicks,'Not payments'),metric('Ticket clicks',a.ticket_clicks,'Not purchases')));
 const money=(n,c='usd')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c.toUpperCase()}).format(n/100);main.append(el('h2',{},'Revenue by category'));if(!d.revenue.length)main.append(el('p',{},d.revenue_available?'No confirmed charges for this selection.':'Payment totals unavailable.'));for(const group of d.revenue)main.append(el('section',{class:'panel'},el('h3',{},group.category+' · '+group.currency.toUpperCase()),el('div',{class:'grid'},metric('Gross collected',money(group.gross,group.currency),group.count+' confirmed payments'),metric('Refunded',money(group.refunded,group.currency),'Refunds reported by Stripe'),metric('After refunds',money(group.net_before_fees,group.currency),'Before processing fees, taxes and costs'),metric('Processing fees',group.fees_known?money(group.fees,group.currency):'Unavailable','Original charge fees'))));main.append(el('p',{class:'muted'},d.unassigned_transactions+' transactions have no reliable site assignment; these appear only in All websites.'));
 main.append(el('h2',{},'Live sessions'));for(const stream of d.streams)main.append(el('article',{class:'card'},el('h3',{},stream.title),el('p',{},brands[stream.site][0]+' · '+stream.state),el('p',{},stream.sessions+' sessions · '+(stream.watch_seconds/60).toFixed(1)+' minutes viewed'),el('p',{},'Started: '+stamp(stream.started_at)+' · Ended: '+stamp(stream.ended_at))));main.append(el('h2',{},'Payment ledger'));for(const t of d.transactions.slice(0,100))main.append(el('div',{class:'card'},el('strong',{},t.category+' · '+money(t.gross,t.currency)),el('p',{},stamp(t.date)+' · '+(brands[t.site]?.[0]||'Unassigned')),el('small',{},t.id+(t.disputed?' · Disputed':''))));for(const note of d.notes)main.append(el('p',{class:'muted'},note));main.append(btn('Export report JSON',()=>download(d,'statistics-'+scope+'.json'),'secondary'),btn('Export payments CSV',()=>download(csv([['Date','Site','Category','Currency','Gross cents','Refunded cents','Original fee cents','Stripe charge'],...d.transactions.map(t=>[t.date,t.site||'Unassigned',t.category,t.currency,t.gross,t.refunded,t.fees??'',t.id])]),'payments-'+scope+'.csv','text/csv'),'secondary'),el('p',{class:'muted'},'Updated '+stamp(d.generated_at)));}


async function giftBenefitsDialog(){
 const data=await api('gift-benefits?site='+site),users=new Map();
 for(const a of [...data.accounts,...data.artists]){const prior=users.get(a.owner_id);users.set(a.owner_id,{...prior,...a,display_name:a.display_name||prior?.display_name||a.owner_id});}
 const list=el('div',{},el('p',{},'Approved staff and artists receive complimentary gifts by default. Customers pay full price unless you select a benefit here. Gift benefits do not include paid viewing or a subscription.'));
 for(const [id,a]of users){const prior=data.benefits.find(x=>x.owner_id===id),choice=select('benefit','Gift benefit',[['default','Default for approved role'],['full','Full price'],['half','50% off'],['complimentary','Complimentary']],prior?.benefit||'default');list.append(el('section',{class:'card'},el('strong',{},a.display_name),el('small',{},'Account: '+id),choice,btn('Save benefit',async()=>{await api('gift-benefits',{site,owner_id:id,benefit:choice.querySelector('select').value});say('Gift benefit saved for this website.');},'secondary')));}
 if(!users.size)list.append(el('p',{},'No approved accounts on this website yet.'));
 const readiness=el('p',{},'Paid gifts: '+(data.paid_enabled?'enabled':'not enabled'));list.append(readiness,btn('Check gift payment connection',async()=>{const r=await api('gift-readiness');readiness.textContent='Payment connection: '+(r.provider_connected?'verified':'needs attention')+' · Taking payments: '+(r.charges_enabled?'allowed':'not verified')+' · Gift webhook events: '+(r.webhook_events_ready?'configured':'needs attention')+' · Gift payments: '+(r.enabled?'enabled':'off');},'secondary'));
 modal('Live gift benefits · '+brands[site][0],list);
}
async function liveRevenueDialog(r){
 const data=await api('live-ledger?id='+r.id),money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100),rows=[...data.gifts.map(x=>({...x,type:'Gift '+(x.gift_code||''),amount_cents:x.amount_cents})),...data.tickets.map(x=>({...x,type:'One-live ticket'}))].sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const list=el('div',{},el('p',{},data.note),el('p',{},'Website: '+brands[data.site][0]),...rows.map(x=>el('article',{class:'card'},el('strong',{},x.type+' · '+(x.status==='complimentary'?'Complimentary':money(x.amount_cents))),el('p',{},x.status+(x.refund_status?' · refund '+x.refund_status:'')),el('small',{},stamp(x.created_at)+' · Account '+x.owner_id))));
 if(!rows.length)list.append(el('p',{},'No gift or ticket orders for this broadcast.'));
 list.append(btn('Export this live’s orders',()=>download(data,'live-revenue-'+r.id+'.json'),'secondary'));modal(r.data.title+' · Live revenue',list);
}

function openInvitedGuest(){if(!pendingGuestInvite){say('Open the complete private invitation sent by the host.');return;}if(!token){title('PRIVATE INVITATION','Sign in to join the live','Use your registered customer or approved artist/staff account. The host will then accept your request.');main.append(btn('Sign in',login,'gold'));return;}history.replaceState(null,'',location.pathname+location.search);phoneStudio=openGuestStudio({api,invite:pendingGuestInvite,onClose:()=>phoneStudio=null});}

function eventLabel(event){return 'Event '+event.local_day+' · ends '+new Date(event.ends_at).toLocaleString('en-US',{timeZone:event.timezone})+' ('+event.timezone+') · original seven-hour window';}
function continuationDialog(r){modal('Continue with existing passes',el('p',{},'Approve a replacement live for this same artist and site. Customers who already paid for this event can enter with the same account. This does not extend their time.'),el('p',{},eventLabel(r.event)),btn('Approve replacement live',async()=>{const next=await api('stream',{site:r.site,title:r.data.title,description:r.data.description||'',audience:r.audience});await api('continuation',{id:next.id,event_id:r.event.id});dialog.close();await load();liveSetup(next);},'gold'));}
