import {siteFetch as fetch,currentSite,apiOrigin,localLink,startGoogle,clearSession,saveSession} from './site-context.js?v=20261010-cover';
let loading;
export async function botCheck(sitekey,action='account'){
 if(!sitekey)return '';
 if(!loading)loading=new Promise((resolve,reject)=>{if(window.turnstile){resolve();return;}const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=resolve;script.onerror=()=>{loading=null;reject(Error('Bot verification could not load. Please try again.'));};document.head.append(script);});
 await loading;
 return new Promise((resolve,reject)=>{const panel=document.createElement('dialog'),heading=document.createElement('h2'),note=document.createElement('p'),box=document.createElement('div'),close=document.createElement('button');heading.textContent='Quick security check';note.textContent='Complete the verification to continue.';close.textContent='Cancel';close.type='button';panel.style.cssText='background:#171320;color:#fff;border:1px solid #ffffff40;border-radius:20px;padding:24px;max-width:90vw';panel.append(heading,note,box,close);document.body.append(panel);let widget,done=false;const finish=(err,token)=>{if(done)return;done=true;clearTimeout(timer);if(widget!==undefined)window.turnstile.remove(widget);panel.close();panel.remove();err?reject(err):resolve(token);};const timer=setTimeout(()=>finish(Error('Verification timed out. Please try again.')),180000);close.onclick=()=>finish(Error('Verification cancelled.'));panel.oncancel=e=>{e.preventDefault();finish(Error('Verification cancelled.'));};panel.showModal();widget=window.turnstile.render(box,{sitekey,action,theme:'auto',callback:token=>finish(null,token),'error-callback':()=>{finish(Error('Verification failed. Please try again.'));return true;},'expired-callback':()=>finish(Error('Verification expired. Please try again.'))});});
}
export async function accountBotCheck(){const r=await fetch('/api/addon/config');if(!r.ok)throw Error('Cannot load security settings. Try again.');return botCheck((await r.json()).turnstileSiteKey,'account');}
