import {siteFetch as fetch,currentSite,apiOrigin,localLink,startGoogle,clearSession,saveSession} from './site-context.js';
import {mountLiveGifts} from './live-gifts.js?v=20261010-gifts';
import {liveShareButton} from './live-share.js?v=20261010-share';
import {createCamera,createLiveMixer} from './live-camera.js?v=20261010-camera';
import {createMediaSender} from './live-media-sender.js?v=20261010-stability';
import {openHostGuests,openGuestConnection} from './live-guests.js?v=20261010-stability';

function element(tag,text,className){const node=document.createElement(tag);if(text)node.textContent=text;if(className)node.className=className;return node;}
function button(text,action,className=''){const b=element('button',text,className);b.type='button';b.onclick=action;return b;}
function select(label,choices){const wrap=element('label',label),input=element('select');for(const[value,title]of choices){const o=element('option',title);o.value=value;input.append(o);}wrap.append(input);return {wrap,input};}
function setup({title,guest=false}){
 if(!document.querySelector('link[data-live-studio]')){const css=element('link');css.rel='stylesheet';css.href='/account-assets/live-studio.css?v=20261010-stability';css.dataset.liveStudio='1';document.head.append(css);}
 const dialog=element('dialog',null,'rr-live'),header=element('header',null,'rr-live-header'),heading=element('h2',guest?'Join the live':'Your live studio'),close=button('✕',null,'rr-live-close');close.setAttribute('aria-label','Close studio');header.append(heading,close);
 const stage=element('div',null,'rr-live-stage'),preview=element('video');preview.muted=true;preview.autoplay=true;preview.playsInline=true;preview.setAttribute('aria-label','Live preview');
 const placeholder=element('div','Press the red button. Allow your camera and microphone when asked.','rr-live-placeholder'),badge=element('span','PREVIEW','rr-live-badge'),clock=element('span','', 'rr-live-clock');stage.append(preview,placeholder,badge,clock);
 const status=element('p','Opening studio…','rr-live-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 const tools=element('div',null,'rr-live-tools'),mic=button('Mic on',null),cam=button('Camera on',null),guests=button('Guests',null),options=button('Options',null);tools.append(mic,cam);if(!guest)tools.append(guests);tools.append(options);
 const settings=element('section',null,'rr-live-options');settings.hidden=true;const camera=select('Camera',[['front','Front camera'],['back','Back camera'],['both','Both cameras']]),layout=select('Both-camera layout',[['stack','Top and bottom'],['side','Side by side']]),apply=button('Apply cameras',null);layout.wrap.hidden=true;camera.input.onchange=()=>layout.wrap.hidden=camera.input.value!=='both';settings.append(camera.wrap,layout.wrap,apply,element('small','Both cameras splits the screen only when two live cameras are supported. iPhone Safari uses one camera at a time.'));
 const people=element('section',null,'rr-live-people');people.hidden=true;const name=element('input');name.type='text';name.maxLength=guest?40:200;name.placeholder=guest?'Your name':'Live title (optional)';name.setAttribute('aria-label',name.placeholder);name.value=guest?'':title||'';
 const primary=button(guest?'Request to join':'Go live',null,'rr-live-primary');primary.disabled=true;const footer=element('footer',null,'rr-live-footer');footer.append(name,primary,element('small',guest?'Your camera stays private until the host accepts you.':'Keep this page open and your phone unlocked. Each event lasts up to seven hours.'));
 dialog.append(header,stage,status,tools,settings,people,footer);document.body.append(dialog);dialog.showModal();options.onclick=()=>settings.hidden=!settings.hidden;guests.onclick=()=>people.hidden=!people.hidden;
 return {dialog,close,preview,placeholder,badge,clock,status,mic,cam,guests,options,settings,camera,layout,apply,people,name,primary};
}
function controls(ui,camera,notice){let muted=false,hidden=false;ui.mic.onclick=()=>{muted=!muted;camera.mute(muted);ui.mic.textContent=muted?'Mic off':'Mic on';ui.mic.setAttribute('aria-pressed',String(muted));};ui.cam.onclick=()=>{hidden=!hidden;camera.hide(hidden);ui.cam.textContent=hidden?'Camera off':'Camera on';ui.cam.setAttribute('aria-pressed',String(hidden));};ui.apply.onclick=async()=>{ui.apply.disabled=true;try{const result=await camera.apply(ui.camera.input.value,ui.layout.input.value);ui.placeholder.hidden=true;notice(result.dual?'Both cameras are live.':'Camera updated.');}catch(e){notice(e.message);}finally{ui.apply.disabled=false;ui.camera.input.value=camera.state().mode;ui.layout.wrap.hidden=ui.camera.input.value!=='both';}};}
function cameraError(e){return e.name==='NotAllowedError'?'Allow camera and microphone access in your browser, then press Go live again.':e.name==='NotFoundError'?'Connect a camera and microphone, then try again.':e.message||'The camera could not start.';}
function time(seconds){return [Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map((n,i)=>i===0?String(n):String(n).padStart(2,'0')).join(':');}

export function openPhoneStudio({record=null,site=record?.site,config={},api,onClose=()=>{}}){
 const ui=setup({title:record?.data?.title}),notice=text=>ui.status.textContent=text;
 const share=liveShareButton({host:true,getRecord:()=>api('watch?id='+record.id),onNotice:notice});share.disabled=true;const pause=button('Pause live',()=>void stop('Live paused. Reopen this session to reconnect; passes keep the original seven-hour deadline.',false));pause.disabled=true;ui.dialog.querySelector('.rr-live-tools').append(share,pause);
 let eventDeadline=0;let giftsUI,camera,mixer,group,groupPromise,recorder,socket,sender,timer,flushTimer,wakeLock,closed=false,starting=false,started=false,confirmed=false,ending=false,ended=false,ready=false,startedAt=0;
 let creatingRecord;
 async function ensureRecord(){if(record)return record;if(!creatingRecord)creatingRecord=api('stream',{site,title:ui.name.value.trim()||'I’m live. Tap in.',description:'',audience:'public'}).then(r=>{record=r;ui.name.disabled=true;return r;}).finally(()=>creatingRecord=null);return creatingRecord;}
 function setPreview(){ui.preview.srcObject=mixer.stream;ui.preview.play().catch(()=>{});ui.placeholder.hidden=true;}
 function refresh(){pause.disabled=!started||ending||ended||closed;share.hidden=!!record&&record.audience!=='public';share.disabled=!confirmed||ending||ended||closed;ui.primary.disabled=!ready||starting||ending||closed;ui.primary.textContent=ended?'Close':starting?'Connecting…':started?'End event':'Go live';ui.primary.classList.toggle('ending',started);ui.badge.textContent=ended?'ENDED':confirmed?'LIVE':starting||started?'CONNECTING':'PREVIEW';ui.badge.classList.toggle('is-live',confirmed);ui.name.disabled=!!record||starting||started;}
 function people(list){ui.people.replaceChildren();const waiting=list.filter(p=>!p.approved),active=list.filter(p=>p.approved);ui.guests.disabled=!config.group_live?.enabled;ui.guests.textContent=waiting.length?'Requests ('+waiting.length+')':'Guests ('+active.length+'/3)';ui.people.append(element('h3','Guests · host + 3 people'),button('Invite guest',invite));if(waiting.length)ui.people.append(element('h4','Join requests'));for(const p of list){const row=element('div',null,'rr-live-person');row.append(element('span',p.name));if(!p.approved)row.append(button('Accept',()=>group?.act('accept',p.id)),button('Decline',()=>group?.act('reject',p.id)));else row.append(button(p.muted?'Unmute':'Mute',()=>group?.act('mute',p.id,!p.muted)),button('Remove',()=>group?.act('remove',p.id)));ui.people.append(row);}if(!list.length)ui.people.append(element('p','Invite someone, or accept a viewer’s request here. You stay full screen until a guest connects.'));}
 async function ensureGroup(){if(group)return group;if(groupPromise)return groupPromise;if(!config.group_live?.enabled)throw Error('Guest connections are not available yet. Solo broadcasting is ready.');groupPromise=(async()=>{const r=await ensureRecord();const connected=await openHostGuests({record:r,api,mixer,onPeople:people,onNotice:notice,onClosed:()=>{group=null;if(!ending&&!closed)notice('Guest connections ended. Your solo video remains available.');}});if(closed){await connected.close();throw Error('Studio closed.');}group=connected;return connected;})().finally(()=>groupPromise=null);return groupPromise;}
 async function invite(){try{const g=await ensureGroup(),url=await g.invite();const field=element('input');field.readOnly=true;field.value=url;field.setAttribute('aria-label','Private guest invitation');const box=element('div',null,'rr-live-invitation');box.append(element('p','Send this private link to your guest. It works once, expires in 15 minutes, and you still approve them.'),field,button('Copy invitation',async()=>{try{await navigator.clipboard.writeText(url);notice('Invitation copied. Send it to your guest.');}catch{field.select();notice('Select and copy the invitation above.');}}));ui.people.querySelector('.rr-live-invitation')?.remove();ui.people.append(box);ui.people.hidden=false;}catch(e){notice(e.message);}}
 async function stop(reason,permanent=!reason){
  if(ending||ended)return;giftsUI?.destroy();giftsUI=null;document.querySelector('dialog.rr-share')?.close();ending=true;confirmed=false;clearInterval(timer);clearInterval(flushTimer);sender?.close();refresh();
  if(recorder&&recorder.state!=='inactive')recorder.stop();recorder=null;
  if(socket){socket.onclose=null;socket.onerror=null;socket.close();socket=null;}
  if(group){await group.close();group=null;}
  if(started&&record)await api('end',{id:record.id,permanent}).catch(()=>notice('Connection stopped. Refresh Live Control to confirm the session ended.'));
  started=false;starting=false;ended=true;camera?.dispose();await mixer?.dispose();await wakeLock?.release().catch(()=>{});ending=false;ui.badge.textContent='ENDED';refresh();notice(reason||'Live ended. Your session record is saved. Server recording is off.');
 }
 async function go(){
  if(ended)return dispose();if(started)return stop();if(starting||!ready)return;
  starting=true;refresh();notice('Allow your camera and microphone when your browser asks.');
  try{
   const audioReady=mixer.resume();await camera.start();if(closed)return;await audioReady;mixer.set('host',camera.stream,'Host');setPreview();
   const r=await ensureRecord();if(closed)return;
   if(config.group_live?.enabled)await ensureGroup();
   if(!window.MediaRecorder)throw Error('Please use an updated Safari or Chrome to broadcast.');
   const mime=['video/webm;codecs=vp8,opus','video/webm','video/mp4'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime)throw Error('This browser cannot broadcast. Please try an updated Safari or Chrome.');
   notice('Connecting your live…');const session=await api('browser-session',{id:r.id});started=true;if(closed){await stop();return;}
   const url=new URL(session.path,apiOrigin);if(url.origin!==apiOrigin||url.pathname!=='/api/addon/browser-live/socket')throw Error('Invalid live connection.');url.protocol='wss:';socket=new WebSocket(url);
   await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Connection timed out. Please open a new live studio and try again.')),15000);const fail=()=>{clearTimeout(timeout);reject(Error('The live connection could not start.'));};socket.onopen=()=>socket.send(JSON.stringify({ticket:session.ticket}));socket.onerror=socket.onclose=fail;socket.onmessage=e=>{try{if(JSON.parse(e.data).type==='ready'){clearTimeout(timeout);resolve();}}catch{fail();}};});
   if(closed){await stop();return;}socket.onclose=e=>{if(!ending&&!closed)void stop(e.reason==='authorization-unavailable'?'The live was ended or access is no longer available.':'The connection to the live server was interrupted. Reopen this session in Live Studio to reconnect. Your viewers keep their passes.');};socket.onerror=()=>{if(!ending)notice('Checking your connection…');};
   sender=createMediaSender({socket,onError:message=>void stop(message)});
   recorder=new MediaRecorder(mixer.stream,{mimeType:mime,videoBitsPerSecond:900000,audioBitsPerSecond:96000});recorder.ondataavailable=e=>{if(!ending&&!closed&&e.data.size)sender.push(e.data);};recorder.onerror=()=>void stop('Your browser stopped capturing video. Reopen this session in Live Studio to reconnect. Your viewers keep their passes.');recorder.start(1000);startedAt=Date.now();
   flushTimer=setInterval(()=>{if(recorder?.state==='recording')try{recorder.requestData();}catch{}},2000);
   notice('Connecting · waiting for your video to arrive.');try{wakeLock=await navigator.wakeLock?.request('screen');}catch{}
   let checking=false,lastCheck=0;timer=setInterval(async()=>{const elapsed=Math.floor((Date.now()-startedAt)/1000);ui.clock.textContent=eventDeadline?time(Math.max(0,Math.floor((eventDeadline-Date.now())/1000)))+' left':time(elapsed);if(checking||Date.now()-lastCheck<5000)return;checking=true;lastCheck=Date.now();try{const state=await api('watch?id='+r.id);if(state.event)eventDeadline=Date.now()+state.event.remaining_seconds*1000;if(state.state==='live'){record={...record,audience:state.audience};confirmed=true;if(!giftsUI)giftsUI=mountLiveGifts({stage:ui.dialog.querySelector('.rr-live-stage'),container:ui.dialog,api,id:r.id,site:r.site,signedIn:true,receiveOnly:true});notice('You’re live. Your audience can watch on the website.');refresh();}else if(['ended','hidden','deleted','failed'].includes(state.state))await stop('This live session has ended. Open a new studio to start again.');else{confirmed=false;refresh();notice('Connecting · waiting for your video to arrive.');}}catch{notice('Checking your live connection…');}finally{checking=false;}},1000);
  }catch(e){if(started)await stop();notice(cameraError(e));}finally{starting=false;refresh();}
 }
 async function dispose(){if(closed)return;if((started||starting)&&!confirm('Close the studio and end your live?'))return;closed=true;if(started)await stop();else{camera?.dispose();await group?.close();await mixer?.dispose();}ui.dialog.close();ui.dialog.remove();window.removeEventListener('pagehide',pagehide);window.removeEventListener('beforeunload',beforeunload);onClose();}
 const pagehide=()=>{camera?.dispose();socket?.close();void group?.close();};const beforeunload=e=>{if(started||starting){e.preventDefault();e.returnValue='';}};
 try{camera=createCamera({onNotice:text=>{notice(text);ui.camera.input.value=camera.state().mode;ui.layout.wrap.hidden=ui.camera.input.value!=='both';}});mixer=createLiveMixer();mixer.set('host',camera.stream,'Host');ui.preview.srcObject=mixer.stream;controls(ui,camera,notice);people([]);ui.primary.onclick=go;ui.close.onclick=dispose;ui.dialog.addEventListener('cancel',e=>{e.preventDefault();void dispose();});api('browser-status').then(value=>{if(closed)return;ready=value.enabled===true;notice(ready?'Ready. Press Go live to start.':'The live server is unavailable. Please try again shortly.');refresh();}).catch(e=>notice(e.message));}catch(e){notice(e.message);ui.close.onclick=()=>{ui.dialog.close();ui.dialog.remove();onClose();};}
 window.addEventListener('pagehide',pagehide);window.addEventListener('beforeunload',beforeunload);
 return {dispose};
}

export function openGuestStudio({api,recordId,invite,onClose=()=>{}}){
 const ui=setup({guest:true}),notice=t=>ui.status.textContent=t;let camera,connection,closed=false,requested=false,busy=false;
 const leave=()=>{if(closed)return;closed=true;connection?.close();camera?.dispose();ui.dialog.close();ui.dialog.remove();window.removeEventListener('pagehide',leave);onClose();};
 try{camera=createCamera({onNotice:text=>{notice(text);ui.camera.input.value=camera.state().mode;ui.layout.wrap.hidden=ui.camera.input.value!=='both';}});ui.preview.srcObject=camera.stream;controls(ui,camera,notice);ui.primary.disabled=false;notice('Enter your name, then press Request to join. Your camera stays private until accepted.');ui.primary.onclick=async()=>{if(requested)return leave();if(busy)return;if(!ui.name.value.trim()){notice('Enter your name first.');ui.name.focus();return;}busy=true;ui.primary.disabled=true;try{await camera.start();if(closed)return;ui.placeholder.hidden=true;await ui.preview.play();const session=await api(invite?'group-join':'group-request',invite?{invite,name:ui.name.value,displayName:ui.name.value}:{id:recordId,name:ui.name.value});if(closed)return;connection=await openGuestConnection({session,camera,onStream:stream=>{ui.preview.onplaying=()=>{ui.badge.textContent='IN STUDIO';};ui.preview.srcObject=stream;ui.preview.muted=false;ui.preview.play().catch(()=>notice('Tap the preview to hear the live.'));},onNotice:notice,onAccepted:()=>{ui.badge.textContent='CONNECTING';notice('The host accepted you. Connecting your camera…');},onClosed:()=>{camera.dispose();ui.badge.textContent='ENDED';ui.badge.classList.remove('is-live');},});if(closed){connection.close();return;}requested=true;ui.primary.textContent='Leave';ui.name.disabled=true;notice('Request sent. Your preview stays private until the host accepts.');}catch(e){notice(cameraError(e));}finally{busy=false;ui.primary.disabled=false;}};ui.preview.onclick=()=>ui.preview.play().catch(()=>{});}catch(e){notice(e.message);}
 ui.close.onclick=leave;ui.dialog.addEventListener('cancel',e=>{e.preventDefault();leave();});window.addEventListener('pagehide',leave);return {dispose:leave};
}
