import {siteFetch as fetch,currentSite,apiOrigin,localLink,startGoogle,clearSession,saveSession} from './site-context.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(path,body){const r=await fetch('/api/radio/'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json','X-Rich-Row-Request':'1'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed.');return d;}
const input=(name,label,value='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='datetime-local'?'required':''}></label>`;
const check=(name,label,value)=>`<label><input name="${name}" type="checkbox" ${value?'checked':''}> ${label}</label>`;
const local=d=>{const v=new Date(d);return new Date(v-v.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export async function mountRadio(root){
 let state;root.innerHTML='<p role="status">Loading radio management…</p>';
 try{state=await call('admin');}catch(e){root.textContent=e.message;return;}
 function draw(){if(!root.isConnected)return;
 root.innerHTML=`<div class="notice">Radio changes are saved on your private server. Broadcast software must be connected separately. A mode label does not start or stop audio.</div><p role="status" id="rr-message"></p><section class="panel"><h2>Station &amp; current broadcast</h2><form id="rr-station">${input('listenUrl','Public listening URL (HTTPS MP3/AAC)',state.station.listenUrl,'url')}${input('ingestUrl','Broadcast server address (no key)',state.station.ingestUrl)}${input('onAir','Current on-air information',state.station.onAir)}<label>Display status<select name="mode">${['offline','live','autodj'].map(x=>`<option ${state.station.mode===x?'selected':''}>${x}</option>`).join('')}</select></label>${check('autoDJ','AutoDJ fallback configured on media server',state.station.autoDJ)}${check('recording','Request automatic recording from media server',state.station.recording)}<button class="primary">Save station</button></form></section><section class="panel"><h2>DJs &amp; private credentials</h2><button class="secondary" id="rr-new-dj">Add DJ</button><div>${state.djs.map(d=>`<article class="live-record"><div><h3>${esc(d.name)}</h3><p>${d.enabled?'Enabled':'Disabled'} · ${d.enforceSlots?'Scheduled slots only':'Any time'} · ${d.hasKey?'Key created':'No key'}</p></div><button data-edit-dj="${d.id}">Edit</button><button data-key="${d.id}" data-action="rotate">Create / rotate key</button><button data-key="${d.id}" data-action="reveal">Show key</button><button data-key="${d.id}" data-action="revoke">Revoke</button></article>`).join('')}</div></section><section class="panel"><h2>DJ slots</h2><p>Enter times in this device’s timezone. Saved times use UTC. Overlapping slots are rejected.</p><button class="secondary" id="rr-new-slot">Schedule slot</button>${state.slots.map(x=>row(x,'slots')).join('')}</section><section class="panel"><h2>Broadcasts &amp; replay publishing</h2><p>Media-server events create recording metadata automatically when an adapter is connected. You can also manage recordings here. Ready recordings remain private until published.</p><button class="secondary" id="rr-new-show">Add broadcast / replay</button>${state.broadcasts.map(x=>row(x,'broadcasts')).join('')}</section><section class="panel" id="rr-editor" hidden></section>`;
 root.querySelector('#rr-station').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await save({...state,station:{...Object.fromEntries(f),autoDJ:f.has('autoDJ'),recording:f.has('recording')}});};
 root.querySelector('#rr-new-dj').onclick=()=>editDJ();root.querySelectorAll('[data-edit-dj]').forEach(b=>b.onclick=()=>editDJ(state.djs.find(x=>x.id===b.dataset.editDj)));
 root.querySelector('#rr-new-slot').onclick=()=>edit('slots');root.querySelector('#rr-new-show').onclick=()=>edit('broadcasts');root.querySelectorAll('[data-edit-item]').forEach(b=>b.onclick=()=>edit(b.dataset.kind,state[b.dataset.kind].find(x=>x.id===b.dataset.editItem)));
 root.querySelectorAll('[data-key]').forEach(b=>b.onclick=async()=>{try{b.disabled=true;const d=await call('key',{djId:b.dataset.key,action:b.dataset.action});state=await call('admin');draw();if(d.key){const box=editor('<h2>Private DJ connection</h2><p>Share only with this DJ through a private channel. Closing this panel removes the displayed key. Rotation invalidates the previous key for new connections.</p>'+input('server','Server',d.ingestUrl)+input('key','Stream key / source password',d.key,'password')+'<button id="rr-copy">Copy key</button><button id="rr-close-key">Close</button>');box.querySelectorAll('input').forEach(i=>i.readOnly=true);box.querySelector('#rr-copy').onclick=async()=>{try{await navigator.clipboard.writeText(d.key);message('Key copied. Keep it private.');}catch{box.querySelector('[name=key]').type='text';message('Select and copy the displayed key.');}};box.querySelector('#rr-close-key').onclick=()=>{box.replaceChildren();box.hidden=true;};setTimeout(()=>{if(box.isConnected){box.replaceChildren();box.hidden=true;}},60000);}else message('Key revoked. Disconnect any active media session separately.');}catch(e){message(e.message);}finally{b.disabled=false;}});
 }
 function message(t){const n=root.querySelector('#rr-message');if(n)n.textContent=t;}
 function row(x,kind){return `<article class="live-record"><div><h3>${esc(x.title)}</h3><p>${esc(new Date(x.start).toLocaleString())} · ${esc(x.status||'Scheduled')} · ${x.published?'Published':'Private'}</p></div><button data-edit-item="${x.id}" data-kind="${kind}">Edit</button></article>`;}
 function editor(html){const box=root.querySelector('#rr-editor');box.innerHTML=html;box.hidden=false;box.scrollIntoView({behavior:'smooth'});return box;}
 async function save(next){root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await call('admin',next);state=await call('admin');draw();message('Saved.');}catch(e){message(e.message);root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 function editDJ(d={id:crypto.randomUUID(),name:'',enabled:true,enforceSlots:true}){const box=editor(`<h2>DJ</h2><form>${input('name','Display name',d.name)}${check('enabled','Allow broadcasts',d.enabled)}${check('enforceSlots','Only allow connection during assigned slots',d.enforceSlots)}<button class="primary">Save DJ</button></form>`);box.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const r={...d,name:f.get('name'),enabled:f.has('enabled'),enforceSlots:f.has('enforceSlots')};save({...state,djs:[...state.djs.filter(x=>x.id!==d.id),r]});};}
 function edit(kind,r={id:crypto.randomUUID(),djId:state.djs[0]?.id||'',title:'',start:new Date().toISOString(),end:new Date(Date.now()+3600000).toISOString(),published:false,status:'planned',description:'',replayUrl:''}){if(!state.djs.length){message('Add a DJ first.');return;}const box=editor(`<h2>${kind==='slots'?'DJ slot':'Broadcast / replay'}</h2><form>${input('title','Title',r.title)}<label>DJ<select name="djId">${state.djs.map(d=>`<option value="${d.id}" ${d.id===r.djId?'selected':''}>${esc(d.name)}</option>`).join('')}</select></label>${input('start','Start',local(r.start),'datetime-local')}${input('end','End',local(r.end),'datetime-local')}${kind==='broadcasts'?`<label>Status<select name="status">${['planned','live','ended','processing','ready','failed'].map(x=>`<option ${r.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Description<textarea name="description">${esc(r.description)}</textarea></label>${input('replayUrl','Public recording URL (HTTPS)',r.replayUrl,'url')}`:''}${check('published',kind==='slots'?'Show slot publicly':'Publish replay publicly',r.published)}<button class="primary">Save</button></form>`);box.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const next={...r,...Object.fromEntries(f),start:new Date(f.get('start')).toISOString(),end:new Date(f.get('end')).toISOString(),published:f.has('published')};save({...state,[kind]:[...state[kind].filter(x=>x.id!==r.id),next]});};}
 draw();
}

