import {siteFetch as fetch,currentSite,apiOrigin,localLink,startGoogle,clearSession,saveSession} from './site-context.js?v=20261010-cover';
import {addToCart,purchaseNow} from './rr-cart-state.js?v=20261010-cover';
export async function bookingPage({main,el,api,button,field,choose,submit,login,getToken,title,say}){
 title('RICH ROW / SESSIONS','Make time for your sound.','Choose your department, date and session. Reserve with cash due at the session, or pay securely by card.');
 const settings=await api('booking-settings');const requestedService=new URLSearchParams(location.search).get('service');let dept=requestedService?.startsWith('photo-')?'photography':requestedService?.startsWith('lounge-')?'lounge':requestedService?.startsWith('video-')?'video':'recording',start='';const panels=el('div'),calendar=el('div'),slots=el('div'),summary=el('div',{class:'panel'}),bookings=el('div');
 const department=choose('department','Department',[['recording','Recording studio'],['video','Video production'],['lounge','Tappin Lounge'],['photography','Photography']],dept);const service=choose('service','Service',[]);const duration=choose('hours','Session length',[]);const date=field('date','Choose a date','','date',true);const timezone=el('p',{class:'muted'});main.append(el('div',{class:'panel'},department,service,duration,date,timezone),calendar,slots,summary,bookings);
 const ds=department.querySelector('select'),ss=service.querySelector('select'),hs=duration.querySelector('select'),di=date.querySelector('input');di.min=new Date().toISOString().slice(0,10);di.max=new Date(Date.now()+179*86400000).toISOString().slice(0,10);di.value=di.min;
 const names={'photo-portrait':'Portraits & headshots — $400','photo-family':'Family photos — $800','photo-event':'Event photography — $300/hour','photo-property':'Real estate photography — $350','photo-commercial':'Commercial & product photography — $2500/day','lounge-day':'Daytime venue access · 3 hours between 9 a.m. and 5 p.m. — $300','lounge-evening':'Showers & children’s events · 5–10 p.m. — $800','lounge-night':'Night event · 10 p.m.–3 a.m. — $2,000',recording:'Recording — $50/hour','video-one':'One-scene performance — $250','video-two':'Two-scene video — $500','video-three':'Three scenes or more — $750'};
 function cfg(){return settings.find(s=>s.department===dept)}
 function durations(){hs.replaceChildren(...(cfg()?.durations?.[ss.value]||[]).map(h=>el('option',{value:String(h)},h+' hour'+(h===1?'':'s'))))}
 function departments(){dept=ds.value;const c=cfg();ss.replaceChildren(...Object.keys(c?.durations||{}).map(k=>el('option',{value:k},names[k]||k)));if(requestedService&&ss.querySelector('option[value="'+CSS.escape(requestedService)+'"]'))ss.value=requestedService;durations();timezone.textContent='All times: '+(c?.timezone||'America/New_York')+(dept==='recording'?'. Three-hour minimum. Five recording hours total per day. Pre-mix included.':'');load();}
 let availabilityRequest=0;async function load(){const request=++availabilityRequest;start='';summary.replaceChildren();slots.replaceChildren();calendar.replaceChildren();const c=cfg();if(!c?.enabled){slots.append(el('p',{},'This department’s online schedule is being prepared. Please contact Rich Row to arrange a session.'));return;}if(!di.value||!hs.value)return;const dateText=new Date(di.value+'T12:00Z').toLocaleDateString('en-US',{dateStyle:'full',timeZone:'UTC'});calendar.append(el('h2',{},dateText));slots.append(el('p',{role:'status'},'Checking availability…'));try{const result=await api('booking-slots?'+new URLSearchParams({department:dept,service:ss.value,date:di.value,hours:hs.value}));if(request!==availabilityRequest)return;slots.replaceChildren(el('p',{},'Choose an available start time'),el('div',{class:'toolbar'},result.slots.map(slot=>button(new Date(slot.start).toLocaleTimeString('en-US',{timeZone:c.timezone,hour:'numeric',minute:'2-digit',timeZoneName:'short'}),()=>select(slot)))));if(result.staffName)calendar.append(el('p',{},'With '+result.staffName));if(!result.slots.length)slots.append(el('p',{},'No sessions of this length are available on this date. Try another date.'));}catch(e){if(request!==availabilityRequest)return;slots.replaceChildren(el('p',{role:'alert'},e.message));}}
 function select(slot){start=slot.start;const h=Number(hs.value),amount=ss.value==='recording'?h*50:ss.value==='video-one'?250:ss.value==='video-two'?500:ss.value==='video-three'?750:({'photo-portrait':400,'photo-family':800,'photo-event':h*300,'photo-property':350,'photo-commercial':2500,'lounge-day':300,'lounge-evening':800,'lounge-night':2000}[ss.value]);const serviceId=ss.value,departmentId=dept;const when=new Date(start).toLocaleString('en-US',{timeZone:cfg().timezone,dateStyle:'full',timeStyle:'short'});summary.replaceChildren(el('h2',{},dept==='lounge'?'Your lounge booking':'Your session'),el('p',{},when+' · '+h+' hour'+(h===1?'':'s')),el('h3',{},'$'+amount+' USD total'));if(dept==='lounge')summary.append(el('p',{},'Tappin Lounge · 5201 Church Avenue, Brooklyn, NY 11203. Venue access only; filming services are not included. Extensions require venue approval: $50 for up to 30 minutes, $100 for 31–60 minutes. Extensions are arranged and paid at the venue, subject to the next booking.'));if(dept==='photography')summary.append(el('p',{},'Photography service. Your booking reserves the selected shooting time. Image selection, delivery details, optional products and any commercial usage rights must be agreed separately. Commercial day length is shown above.'));if(!getToken()){summary.append(button('Sign in or create an account to reserve',login));return;}const f=el('form',{},field('name','Your name','','text',true),field('phone','Phone (optional)','','tel'),field('notes','Additional project details or questions (optional)','','textarea'),choose('payment_method','Payment',[['cash','Pay cash at the session'],['card','Add to cart and pay with Stripe']],'card'));if(departmentId==='lounge')f.append(el('label',{},el('input',{type:'checkbox',name:'cleanup_agreed',required:true}),'I agree to designate someone to clean up after our event and ensure our group leaves the venue clean.'));submit(f,'Add to cart',async d=>{if(d.payment_method==='card'){addToCart({kind:'booking',...d,start:slot.start,hours:h,service:serviceId,department:departmentId});location.assign('/addons/cart');return;}const b=await api('bookings',{...d,start:slot.start,hours:h,service:serviceId,department:departmentId});if(b.url){location.href=b.url;return;}say('Session reserved. Payment is due in cash at your session.');await load();await myBookings();});f.elements.payment_method.addEventListener('change',()=>{f.querySelector('button[type=submit]').textContent=f.elements.payment_method.value==='cash'?'Reserve and pay cash':'Add to cart'});f.append(button('Purchase now by card',()=>{if(!f.reportValidity())return;const details=Object.fromEntries(new FormData(f));return purchaseNow({kind:'booking',...details,start:slot.start,hours:h,service:serviceId,department:departmentId},{api,getToken,login});}));summary.append(f,el('p',{class:'muted'},'The time is confirmed only after your reservation succeeds. Availability is checked again when you reserve. Contact Rich Row about changes.'));}
 async function myBookings(){bookings.replaceChildren();if(!getToken())return;const rows=await api('bookings');bookings.append(el('h2',{},'Your bookings'));for(const b of rows){const c=settings.find(s=>s.department===b.department);bookings.append(el('article',{class:'card'},el('h3',{},names[b.service]||b.service),el('p',{},new Date(b.starts_at).toLocaleString('en-US',{timeZone:c?.timezone||'America/New_York',dateStyle:'full',timeStyle:'short'})),el('p',{},'$'+(b.amount/100)+' · '+({cash_due:'Reserved — cash due',awaiting_payment:'Reserved temporarily — payment pending',paid:'Paid and confirmed',expired:'Payment window expired',review:'Contact studio about payment',refunded:'Refunded',cancelled:'Cancelled'}[b.status]||b.status)),b.status==='awaiting_payment'?button('Continue payment',async()=>{location.href=(await api('booking-pay',{id:b.id})).url;}):null));}}
 ds.onchange=departments;ss.onchange=()=>{durations();load()};hs.onchange=load;di.onchange=load;departments();await myBookings();
}

