import {siteFetch as fetch,currentSite,apiOrigin,localLink,startGoogle,clearSession,saveSession} from './site-context.js';
const sites={richrow:'Rich Row Records',waynekastro:'Wayne Kastro',dracodon17:'Draco Don17',goldenrama440:'Golden Rama'};
export async function connectPage({main,el,api,button,login,getToken,title}){
 const params=new URLSearchParams(location.search),site=params.get('site')||'richrow';if(!Object.hasOwn(sites,site))throw Error('Choose a valid site.');const role=params.get('role')||'staff';if(new URLSearchParams(location.hash.slice(1)).get('type')==='recovery'){title(sites[site],'Reset your password','Use the secure password reset form.');return;}
 if(role==='artist'){location.replace('/portal.html?site='+site+(getToken()?'':'&signin=1'));return;}
 if(role==='customer'){location.replace('/addons/'+(site==='richrow'?'membership':'artist-membership')+'?site='+site+(getToken()?'':'&signin=1'));return;}
 title(sites[site]+' / MANAGER & STAFF','Your manager workspace','Site-specific access, reviewed by Rich Row.');
 if(!getToken()){main.append(el('p',{},'Sign in or register as a manager or staff member for '+sites[site]+'.'),button('Manager / Staff Sign In',login));return;}
 const rows=await api('account-roles?site='+site),staff=rows.find(r=>r.role==='staff');
 if(!staff){main.append(el('p',{},'Request manager/staff access to this website. Approval is required.'),button('Request manager access',async()=>{await api('account-roles',{site,role:'staff'});await connectPage({main,el,api,button,login,getToken,title});}));return;}
 const status={active:'Approved',pending:'Waiting for approval',rejected:'Declined',suspended:'Blocked'}[staff.status]||staff.status;main.append(el('h2',{},status),el('p',{},staff.status==='active'?'Your assigned website workspace is available below.':'The label manages this request in Console → Approvals & Requests → Accounts & staff access.'),button('Refresh status',()=>connectPage({main,el,api,button,login,getToken,title}),'secondary'));
 if(staff.status!=='active')return;main.append(el('p',{},'This manager role can view the assigned catalog. Artist private uploads, billing, and administrator controls require their separate permissions.'),el('a',{href:'https://'+({richrow:'richrowmusic',waynekastro:'waynekastro',dracodon17:'dracodon17',goldenrama440:'goldenrama440'}[site])+'.com',target:'_blank',rel:'noopener',class:'cta'},'Preview public website'));
 main.append(el('a',{href:'/addons/portal?staff=1&site='+site+'&tab=statistics',class:'cta'},'Site Statistics & Revenue'));
 if(staff.can_edit_site)await managerPages({main,el,api,button,site});
 const catalog=await api('staff-catalog?site='+site);main.append(el('h2',{},'Assigned catalog'));if(!catalog.length)main.append(el('p',{},'No catalog releases have been assigned to this site yet.'));for(const item of catalog)main.append(el('article',{class:'card'},el('h3',{},item.title),el('p',{},item.artist+' · '+item.source_status)));
}
export async function accountAdmin({area,el,api,button,say}){
 const rows=await api('admin/account-roles');area.replaceChildren(el('h2',{},'Team access & customer accounts'),el('p',{},'Customers register without approval. Artist back-office access and manager/staff access are controlled by you. There is no application-imposed team-size limit.'));
 const f=el('form',{class:'panel'}),input=(name,label,type='text')=>el('label',{},label,el('input',{name,type,required:name==='email'}));f.append(el('h3',{},'Add a team member'),input('name','Name (optional)'),input('email','Email address','email'),el('label',{},'Website',el('select',{name:'site'},Object.entries(sites).map(([value,label])=>el('option',{value},label)))),el('label',{},'Back-office role',el('select',{name:'role'},el('option',{value:'staff'},'Manager / Staff'),el('option',{value:'artist'},'Artist'))),el('label',{},el('input',{type:'checkbox',name:'can_edit_site',checked:true}),' Allow manager/staff to draft website changes for your approval'),el('p',{},'Add an existing account or email an invitation to a new team member. Only the selected website is assigned. Only you can approve access or publish submitted website changes.'),el('button',{type:'submit'},'Add team member / Send invitation'));f.onsubmit=async e=>{e.preventDefault();if(!f.reportValidity())return;const b=f.querySelector('button');b.disabled=true;try{const d=Object.fromEntries(new FormData(f));d.can_edit_site=f.elements.can_edit_site.checked;const result=await api('admin/team-add',d);say(result.message);f.reset();await accountAdmin({area,el,api,button,say});}catch(err){say(err.message);}finally{b.disabled=false;}};area.append(f);
 const filter=el('select',{'aria-label':'Filter accounts by website'},el('option',{value:''},'All four websites'),Object.entries(sites).map(([value,label])=>el('option',{value},label))),list=el('div');area.append(filter,list);function draw(){list.replaceChildren();const selected=rows.filter(r=>!filter.value||r.site===filter.value).sort((a,b)=>(a.status==='pending'?0:1)-(b.status==='pending'?0:1));for(const r of selected){const role={staff:'Manager / Staff',customer:'Customer',artist:'Artist'}[r.role],status={active:'Approved',pending:'Waiting for approval',rejected:'Declined',suspended:'Blocked'}[r.status];const card=el('article',{class:'card'},el('h3',{},sites[r.site]+' · '+role),el('p',{},r.display_name||r.email||'Account '+r.owner_id),el('p',{},r.email||''),el('strong',{},status),r.self_protected?el('p',{},'Your admin account · protected'):null,r.role==='customer'?el('p',{},'Customer registration is automatic. No approval needed.'):el('p',{},r.can_edit_site?'Can draft website changes; publishing requires your approval.':'Catalog access only until you enable website editing.'));
 const statuses=r.role==='customer'?['active','suspended']:['active','rejected','suspended'];for(const status of statuses.filter(x=>x!==r.status&&(!r.self_protected||x==='active')))card.append(button(status==='active'?(r.status==='suspended'?'Unblock':'Approve'):status==='rejected'?'Decline':'Block',async()=>{await api('admin/account-roles',{id:r.id,site:r.site,status,can_edit_site:r.role==='staff'&&status==='active'});say('Access updated.');await accountAdmin({area,el,api,button,say});}));if(r.role==='staff'&&r.status==='active'&&!r.can_edit_site)card.append(button('Enable website drafting',async()=>{await api('admin/account-roles',{id:r.id,site:r.site,status:'active',can_edit_site:true});await accountAdmin({area,el,api,button,say});}));list.append(card);}if(!selected.length)list.append(el('p',{},'No registered accounts for this filter yet.'));}filter.onchange=draw;draw();
}
async function managerPages({main,el,api,button,site}){
 const rows=await api('staff/pages?site='+site);main.append(el('h2',{},'Website back office'),el('p',{},'Edit page copy and links, then send your changes to the owner for approval. Published pages stay unchanged until approved.'));
 for(const p of rows){const f=el('form',{class:'panel'},el('h3',{},p.title));const draft=structuredClone(p);const input=(label,value,save,multi=false)=>{const node=el(multi?'textarea':'input',{value:value||''});node.oninput=()=>save(node.value);return el('label',{},label,node);};f.append(input('Page title',p.title,v=>draft.title=v));p.blocks.forEach((block,i)=>{const section=el('fieldset',{},el('legend',{},'Section '+(i+1)+' · '+block.type));for(const key of ['title','body','label','url'])if(typeof block[key]==='string')section.append(input(key==='body'?'Text':key==='url'?'Link':key[0].toUpperCase()+key.slice(1),block[key],v=>draft.blocks[i][key]=v,key==='body'));if(section.children.length>1)f.append(section);});const status=el('p',{role:'status'});f.append(status,el('button',{type:'submit'},'Send changes for approval'));f.onsubmit=async e=>{e.preventDefault();const button=f.querySelector('button');button.disabled=true;try{await api('staff/page-proposal',{site,page_id:p.id,revision:p.revision,title:draft.title,blocks:draft.blocks});status.textContent='Changes sent. The owner can approve them in Console → Approvals & Requests → Website changes.';}catch(err){status.textContent=err.message;}finally{button.disabled=false;}};main.append(f);}if(!rows.length)main.append(el('p',{},'No editable pages have been assigned yet.'));
}
export async function siteEditAdmin({area,el,api,button,say}){const rows=await api('admin/site-edits');area.replaceChildren(el('h2',{},'Website change requests'),el('p',{},'Review manager/staff changes before they reach your public website.'));for(const r of rows){const card=el('article',{class:'card'},el('h3',{},sites[r.site]+' · '+r.draft.title),el('p',{},r.status+' · '+new Date(r.created_at).toLocaleString()),el('p',{},'Submitted by account '+r.owner_id));for(const b of r.draft.blocks)if(b.title||b.body||b.label||b.url)card.append(el('section',{class:'panel'},el('strong',{},b.title||b.type),el('p',{class:'prewrap'},b.body||''),el('p',{},b.label||''),el('p',{},b.url||'')));if(r.status==='pending')for(const action of ['approve','decline'])card.append(button(action==='approve'?'Approve & publish':'Decline',async()=>{await api('admin/site-edits',{id:r.id,action});say(action==='approve'?'Website changes published.':'Request declined.');await siteEditAdmin({area,el,api,button,say});}));area.append(card);}if(!rows.length)area.append(el('p',{},'No website change requests yet.'));}

function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function connectorAdmin({area,el,api,button,field,submit,say}){
 const info=await api('admin/labelcaster');area.replaceChildren(el('h2',{},'Labelcaster connector'),el('p',{},'Assisted submission · Official partner access is not configured.'),el('p',{},'Import a JSON array of release metadata from your authorized export. Every release must include artist_site and title. Optional fields: external_id, upc, release_date, status and tracks (title, isrc, explicit). Imports remain private and do not publish or submit music.'));
 const f=el('form',{class:'panel'},field('releases','Release metadata (JSON array)','','textarea',true));submit(f,'Validate & import',async d=>{let releases;try{releases=JSON.parse(d.releases);}catch{throw Error('Enter valid JSON.');}await api('admin/labelcaster-import',{releases});say('Metadata imported.');await connectorAdmin({area,el,api,button,field,submit,say});});area.append(f);
 area.append(button('Download import example',()=>download([{artist_site:'waynekastro',title:'Replace with verified title',external_id:'',upc:'',status:'unknown',tracks:[]}],'labelcaster-import-template.json'),'secondary'));
 for(const r of info.releases)area.append(el('article',{class:'card'},el('h3',{},r.title),el('p',{},r.artist+' · '+r.source_status),el('p',{},'UPC: '+(r.upc||'Not supplied'))));
 const submissions=await api('admin/submissions');area.append(el('h2',{},'Approved releases'));
 for(const s of submissions.filter(s=>s.status==='approved'))area.append(el('article',{class:'card'},el('h3',{},s.title),button('Download delivery manifest',async()=>download(await api('admin/labelcaster-package?id='+s.id),'rich-row-delivery-'+s.id+'.json'))));
 area.append(el('p',{},'The manifest references private masters and artwork. Retrieve those files from the media library for manual delivery. It does not contain audio, artwork, credentials or a DDEX feed.'));
}

