import {siteFetch as fetch,currentSite,apiOrigin,localLink,startGoogle,clearSession,saveSession} from './site-context.js?v=20261010-cover';
const tierNames=[['basic','Live + Gallery ($15)'],['new','Music'],['catalog','Chosen Catalog'],['vault','DJ Vault']];
export async function galleryAdmin({area,el,api,button,field,choose,check,submit,modal,upload,say}){
 const albums=await api('admin/gallery');
 async function editAlbum(a={}){const f=el('form',{},field('title','Event or album name',a.title||'','text',true),field('event_date','Event date',a.event_date||new Date().toISOString().slice(0,10),'date',true),field('description','Description',a.description||'','textarea'),el('h3',{},'Who can view?'),...tierNames.map(([id,name])=>check('view_'+id,name,(a.view_tiers||tierNames.map(t=>t[0])).includes(id))),el('h3',{},'Who can download?'),el('p',{},'Defaults to the $15 Live + Gallery plan. Change these choices whenever you want.'),...tierNames.map(([id,name])=>check('download_'+id,name,(a.download_tiers||['basic']).includes(id))),check('published','Published',a.published===true));submit(f,'Save album',async d=>{await api('admin/gallery',{id:a.id,title:d.title,event_date:d.event_date,description:d.description,published:d.published,view_tiers:tierNames.filter(([id])=>d['view_'+id]).map(t=>t[0]),download_tiers:tierNames.filter(([id])=>d['download_'+id]).map(t=>t[0])});f.closest('dialog').close();await galleryAdmin({area,el,api,button,field,choose,check,submit,modal,upload,say});say('Album saved.');});modal(a.id?'Edit album':'New event album',f);}
 async function items(a){const result=await api('admin/gallery?album='+a.id);area.replaceChildren(button('Back to albums',()=>galleryAdmin({area,el,api,button,field,choose,check,submit,modal,upload,say})),el('h2',{},a.title),el('p',{},a.event_date),button('Add photo or video',()=>editItem(a)));if(!result.items.length)area.append(el('p',{},'Add the first photo or video.'));for(const item of result.items)area.append(el('article',{class:'card'},el('h3',{},item.title||item.kind),el('p',{},(item.captured_on||a.event_date)+(item.hidden?' · Hidden':'')),button('Edit item',()=>editItem(a,item))));}
 async function editItem(a,item={}){const f=el('form',{},field('title','Caption or title',item.title||''),choose('kind','Media type',[['image','Photo'],['video','Video']],item.kind||'image'),field('captured_on','Date taken',item.captured_on||a.event_date,'date'),field('sort_order','Display order',item.sort_order||0,'number'),field('file','Upload photo or video','','file'),field('external_url','Or paste an HTTPS media link',item.external_url||'','url'),el('p',{},'Uploads stay private and use your album permissions. External links remain subject to their own privacy settings. YouTube and Vimeo videos can play here; other video links should point to an MP4 file. Photos need a direct image link. Maximum upload: 50 MB.'),check('hidden','Hide this item',item.hidden===true));f.elements.file.accept='.png,.jpg,.jpeg,.mp4';submit(f,'Save item',async d=>{const file=f.elements.file.files[0];if(file&&d.external_url)throw Error('Choose an upload or a link, not both.');const m=file?await upload(file,'gallery'):null;await api('admin/gallery-item',{...d,album_id:a.id,id:item.id,media_id:m?.id||(!d.external_url?item.media_id:null)});f.closest('dialog').close();await items(a);say('Gallery item saved.');});modal('Photo or video',f);}
 area.replaceChildren(el('h2',{},'Event Gallery'),el('p',{},'Create dated albums, choose membership access and add photos or videos. Leave an album unpublished to keep it private.'),button('New event album',()=>editAlbum()));for(const a of albums)area.append(el('article',{class:'card'},el('h3',{},a.title),el('p',{},a.event_date+' · '+(a.published?'Published':'Draft')),button('Edit album',()=>editAlbum(a)),button('Photos & videos',()=>items(a))));
}
function embedURL(value){try{const u=new URL(value);let id;if(['www.youtube.com','youtube.com','m.youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed)\/([\w-]{11})/)?.[1];if(u.hostname==='youtu.be')id=u.pathname.slice(1);if(/^[\w-]{11}$/.test(id||''))return 'https://www.youtube-nocookie.com/embed/'+id;if(['vimeo.com','www.vimeo.com'].includes(u.hostname)&&/^\/\d+$/.test(u.pathname))return 'https://player.vimeo.com/video'+u.pathname;}catch{}return null;}
export async function galleryPage({main,el,api,button,login,getToken,title}){
 title('RICH ROW / GALLERY','Events. Sessions. Moments.','Explore photos and videos organized by event and date.');main.append(el('a',{class:'cta',href:'/addons/booking?service=photo-portrait'},'Book a photo shoot'));if(!getToken()){main.append(button('Sign in to view albums',login));return;}
 const albumId=new URLSearchParams(location.search).get('album');if(!albumId){const albums=await api('gallery');if(!albums.length)main.append(el('p',{},'Event albums will appear here when published.'));for(const a of albums)main.append(el('article',{class:'card'},el('h2',{},a.title),el('p',{},a.event_date),el('p',{},a.description),el('a',{class:'cta',href:'/addons/gallery?album='+encodeURIComponent(a.id)},'Open album')));return;}
 main.append(el('a',{class:'cta',href:'/addons/gallery'},'All albums'));const data=await api('gallery?album='+encodeURIComponent(albumId));main.append(el('h2',{},data.album.title),el('p',{},data.album.event_date),el('p',{},data.album.description));if(!data.items.length)main.append(el('p',{},'Photos and videos are coming soon.'));for(const item of data.items){const src=item.kind==='video'&&item.external?embedURL(item.url):null;const visual=src?el('iframe',{src,title:item.title||'Event video',allow:'fullscreen; picture-in-picture',allowfullscreen:true,loading:'lazy',style:'width:100%;aspect-ratio:16/9;border:0'}):el(item.kind==='image'?'img':'video',{src:item.url,alt:item.title||'Event photo',controls:item.kind==='video',preload:'none',referrerpolicy:'no-referrer',style:'max-width:100%;max-height:70vh'});const card=el('article',{class:'card'},el('h3',{},item.title||'Event '+item.kind),el('p',{},item.captured_on||data.album.event_date),visual);if(data.permissions.download&&!item.external)card.append(button('Download',async()=>location.assign((await api('gallery-download',{id:item.id})).url)));if(item.external)card.append(el('a',{href:item.url,target:'_blank',rel:'noopener noreferrer',class:'cta'},'Open original'));main.append(card);}
}

