import {siteFetch as fetch,currentSite,apiOrigin,localLink,startGoogle,clearSession,saveSession} from './site-context.js?v=20261010-cover';
import {rosterAccessEditor} from './rr-roster-access.js?v=20261010-cover';
export async function teamAdmin(ctx){
 const {area,el,api,button,field,submit,modal,upload,say}=ctx;
 const profiles=await api('admin/team');
 function edit(p={}){const links=Object.fromEntries((p.links||[]).map(l=>[l.label,l.url]));const preview=el('article',{class:'card'});let localPhoto=p.photo;const f=el('form',{},field('name','Team member name',p.name||'','text',true),field('role','Role or specialties',p.role||''),field('bio','Biography',p.bio||'','textarea'),field('photo','Upload portrait','','file'),el('p',{class:'muted'},'Choose a JPEG or PNG portrait. Portraits use protected storage. Your roster access setting controls who can retrieve them.'),...['website','instagram','youtube','soundcloud'].map(k=>field(k,k[0].toUpperCase()+k.slice(1)+' link',links[k]||'','url')),field('sort_order','Display order (lowest first)',p.sort_order||0,'number'));f.elements.photo.accept='.jpg,.jpeg,.png';f.elements.bio.maxLength=5000;f.elements.name.maxLength=120;let temp;
 const draw=()=>preview.replaceChildren(localPhoto?el('img',{src:localPhoto,alt:f.elements.name.value,style:'width:100%;max-height:280px;object-fit:cover;border-radius:16px'}):el('p',{},'Photo preview'),el('h3',{},f.elements.name.value||'Member name'),el('p',{},f.elements.role.value),el('p',{class:'prewrap'},f.elements.bio.value||'Your biography will appear here.'));f.addEventListener('input',draw);f.elements.photo.addEventListener('change',()=>{if(temp)URL.revokeObjectURL(temp);if(f.elements.photo.files[0])localPhoto=temp=URL.createObjectURL(f.elements.photo.files[0]);draw();});
 async function save(published){if(!f.reportValidity())return;const data=Object.fromEntries(new FormData(f)),file=f.elements.photo.files[0];const photo=file?await upload(file,'gallery'):null;await api('admin/team',{...data,id:p.id,photo_id:photo?.id||p.photo_id||null,published});if(temp)URL.revokeObjectURL(temp);f.closest('dialog').close();await teamAdmin(ctx);say(published?'Team profile published.':'Profile saved as draft.');}
 submit(f,'Save draft',()=>save(false));f.append(button('Publish now',()=>save(true)));draw();modal(p.id?'Edit team member':'Add team member',el('div',{},f,el('h3',{},'Live preview'),preview));}
 area.replaceChildren(el('h2',{},'Team Unstoppable'),el('p',{},'Add team members from every field, upload portraits and tell their stories. Edit any profile whenever you want. Lower display numbers appear first.'),button('+ Add team member',()=>edit()),el('a',{class:'cta',href:'https://richrowmusic.com/team.html',target:'_blank',rel:'noopener'},'View Team Unstoppable'));if(!profiles.length)area.append(el('p',{},'Your team starts here. Add your first team member when ready.'));area.append(await rosterAccessEditor(ctx,'team'));for(const p of profiles)area.append(el('article',{class:'card'},p.photo?el('img',{src:p.photo,alt:p.name,style:'width:90px;height:90px;object-fit:cover;border-radius:16px'}):null,el('h3',{},p.name),el('p',{},p.role+' · '+(p.published?'Published':'Draft')+' · Order '+p.sort_order),button('Edit profile',()=>edit(p)),p.published?button('Unpublish',async()=>{await api('admin/team',{...p,...Object.fromEntries(p.links.map(l=>[l.label,l.url])),published:false});await teamAdmin(ctx);say('Profile moved to drafts.');}):null));
}

