import {siteFetch as fetch,currentSite,apiOrigin,localLink,startGoogle,clearSession,saveSession} from './site-context.js?v=20261010-cover';
import {brandSignIn} from './site-login-brand.js?v=20261010-final';
import {accountBotCheck} from './bot-check.js?v=20261010-cover';
import {waitForVerification} from './auth-verification.js?v=20261010-cover';
// One accessible sign-in experience for artists, customers, staff and admins.
// Authentication callbacks MUST resolve only after the real server accepts them.
export function openSignIn({name='Rich Row',authenticate,signup,recover,resend,onSuccess,admin=false,role='customer',site='richrow'}){
 const origins={richrow:'https://richrowmusic.com',waynekastro:'https://waynekastro.com',dracodon17:'https://dracodon17.com',goldenrama440:'https://goldenrama440.com'};
 if(!admin&&location.hostname==='console.richrowmusic.com'&&origins[site]){location.assign(origins[site]+'/account.html?site='+site+'&role='+(['customer','artist','staff'].includes(role)?role:'customer')+'&signin=1');return;}
 document.querySelector('dialog[data-shared-login]')?.remove();
 const dialog=document.createElement('dialog');dialog.dataset.sharedLogin='';dialog.dataset.consoleLogin=String(admin);
 Object.assign(dialog.style,{padding:'0',border:'1px solid #59456d',borderRadius:'20px',width:'min(1000px,96vw)',maxWidth:'1000px',maxHeight:'94svh',background:'#101016',color:'#f6f4fa',overflow:'auto'});
 const host=document.createElement('div');const root=host.attachShadow({mode:'open'});dialog.append(host);document.body.append(dialog);
 root.innerHTML=`<link rel="stylesheet" href="/account-assets/shared-login.css?v=20261010-cover"><div class="layout"><aside class="art"><div class="brand"><span class="mark" aria-hidden="true">RR</span><span id="brand"></span></div><div class="sculpture" aria-hidden="true"></div><div class="art-copy"><div class="eyebrow">A space for your next chapter</div><h1>Your art.<br>Your people.<br>Your possibility.</h1><p>Bring your ideas, find your rhythm, and make room for what comes next.</p></div></aside><section class="form-side"><button class="exit" type="button" aria-label="Close sign in">✕</button><div class="panel"><div class="tag"><span class="dot"></span><span id="kind">Artist community</span></div><h2 id="heading">Welcome back.</h2><p class="subtitle" id="intro">Sign in to your creative space.</p><form novalidate><div class="field"><div class="label-row"><label for="email">Artist Name or Email</label></div><input id="email" name="email" type="text" autocomplete="username" autocapitalize="none" spellcheck="false" maxlength="254" placeholder="Your account email" aria-describedby="email-help email-error"><small id="email-help" style="display:block;color:#a59eaf;margin-top:7px;font-size:11px">Use your registered email. Artist names are display names.</small><p id="email-error" class="error" hidden></p></div><div class="field" id="password-field"><div class="label-row"><label for="password">Password</label></div><div class="input-wrap"><input id="password" name="password" type="password" autocomplete="current-password" placeholder="Your password" maxlength="1024" aria-describedby="password-error"><button type="button" class="reveal" aria-label="Show password" aria-pressed="false">Show</button></div><p id="password-error" class="error" hidden></p></div><div class="options"><label class="remember"><input id="remember" type="checkbox">Remember Me</label><button class="mini" id="reset" type="button">Forgot password?</button></div><button class="submit" type="submit"><span class="spinner" hidden aria-hidden="true"></span><span id="submit-text">Sign In</span></button><p class="form-error" id="error" role="alert"></p><p class="notice" id="status" role="status" hidden></p></form><p class="signup"><a href="#registration" id="register">Artist Registration / Sign Up</a></p><p class="note">Secure account sign-in. Remember Me saves your email on this device, never your password.</p></div></section></div><div class="overlay" hidden aria-hidden="true"><div class="loading-card"><div class="spinner"></div><p id="loading-title">Signing in…</p><small>Your creative space is almost ready.</small></div></div>`;
 if(admin){const style=document.createElement('style');style.textContent='.google-signin,.submit,.role-tabs,.role-tabs a,.tag,input[type=text],input[type=password]{border-radius:4px}';root.append(style);dialog.style.borderRadius='6px';}
 const $=s=>root.querySelector(s),form=$('form'),email=$('#email'),password=$('#password');let busy=false,mode='signin';
 const artistMember=role==='customer'&&['waynekastro','dracodon17','goldenrama440'].includes(site);
 if(artistMember){$('.mark').textContent=name;const fields=document.createElement('div');fields.id='member-fields';fields.hidden=true;fields.innerHTML='<div class="field"><label for="first_name">First name</label><input id="first_name" autocomplete="given-name" required maxlength="80"></div><div class="field"><label for="last_name">Last name</label><input id="last_name" autocomplete="family-name" required maxlength="80"></div><div class="field"><label for="phone">Phone number</label><input id="phone" type="tel" autocomplete="tel" required maxlength="40"></div><div class="field"><label for="confirm_password">Confirm password</label><input id="confirm_password" type="password" autocomplete="new-password" required></div><label class="remember"><input id="sms_opt_in" type="checkbox" required> I allow membership SMS updates from this artist.</label>';form.insertBefore(fields,$('.options'));}
 $('#brand').textContent=name;const roleName=admin?'Administrator':role==='artist'?'Artist':role==='staff'?'Manager / Staff':'Customer';$('#kind').textContent=roleName+' account';$('#intro').textContent='Sign in to your '+roleName.toLowerCase()+' portal for '+name+'.';root.querySelector('label[for="email"]').textContent=role==='artist'?'Artist Name or Email':'Email address';$('#email-help').textContent=role==='artist'?'Use your registered email. Artist names are display names.':'Use the email registered to your account.';
 const roleLinks=document.createElement('nav');roleLinks.className='role-tabs';roleLinks.setAttribute('aria-label','Account type');const safeSite=['richrow','waynekastro','dracodon17','goldenrama440'].includes(site)?site:'richrow';for(const [key,label,path]of [['customer','Customer',safeSite==='richrow'?'membership':'artist-membership'],['artist','Artist','portal'],['staff','Manager / Staff','connect']]){const a=document.createElement('a');a.textContent=label;a.href='/account.html?site='+safeSite+'&role='+key+'&signin=1';if(!admin&&key===role)a.setAttribute('aria-current','page');roleLinks.append(a);}$('.panel').insertBefore(roleLinks,$('.tag'));
 const google=document.createElement('button');google.type='button';google.className='google-signin';const googleLogo=document.createElement('img');googleLogo.src='https://developers.google.com/static/identity/images/g-logo.png';googleLogo.alt='';googleLogo.width=20;googleLogo.height=20;const googleText=document.createElement('span');googleText.textContent='Continue with Google';google.append(googleLogo,googleText);google.onclick=()=>{if(busy)return;busy=true;google.disabled=true;startGoogle(role).catch(()=>{busy=false;google.disabled=false;});};$('.panel').insertBefore(google,form);
 dialog.setAttribute('aria-label',name+' sign in');
 const read=()=>{try{return localStorage.getItem('rr_remembered_email')||'';}catch{return '';}};
 email.value=read();$('#remember').checked=!!email.value;
 const remember=()=>{try{if($('#remember').checked)localStorage.setItem('rr_remembered_email',email.value.trim());else localStorage.removeItem('rr_remembered_email');}catch{}};
 $('#remember').onchange=()=>{if(!$('#remember').checked)remember();};
 const close=()=>{if(!busy){dialog.close();dialog.remove();}};$('.exit').onclick=close;dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>dialog.remove());
 $('.reveal').onclick=()=>{const show=password.type==='password';password.type=show?'text':'password';$('.reveal').textContent=show?'Hide':'Show';$('.reveal').setAttribute('aria-pressed',String(show));$('.reveal').setAttribute('aria-label',show?'Hide password':'Show password');};
 function validate(input){const message=input===email?(!email.value.trim()?'Enter your account email.':!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value.trim())?'Use the email address registered to your account.':''):mode==='recover'?'':!password.value?'Enter your password.':mode==='signup'&&password.value.length<6?'Choose a password with at least 6 characters.':'';const error=$('#'+input.id+'-error');error.textContent=message;error.hidden=!message;input.setAttribute('aria-invalid',String(!!message));return !message;}
 for(const input of [email,password]){input.onblur=()=>{if(!busy&&input.value)validate(input);};input.oninput=()=>{if(input.getAttribute('aria-invalid')==='true')validate(input);$('#error').textContent='';};}
 function setMode(next){mode=next;if(artistMember)$('#member-fields').hidden=next!=='signup';let guide=root.querySelector('#signup-guide');if(next==='signup'&&!guide){guide=document.createElement('div');guide.id='signup-guide';guide.className='notice';guide.innerHTML='<strong>First time here? Follow these steps:</strong><ol><li>Enter your email address.</li><li>Create a password with at least 6 characters.</li>'+(artistMember?'<li>Enter your first name, last name and phone number.</li><li>Type the same password again and approve SMS membership updates.</li>':'')+'<li>Press Create Account.</li><li>Open the verification email and tap the verification link.</li><li>Return here and sign in.</li></ol>';form.prepend(guide);}if(next!=='signup')guide?.remove();$('#password-field').hidden=next==='recover';$('#heading').textContent=next==='signup'?'Create an account':next==='recover'?'Reset your password':'Sign in';$('#submit-text').textContent=next==='signup'?'Create Account':next==='recover'?'Send Reset Email':'Sign In';$('#register').textContent=next==='signin'?'New here? Create an account':'Back to Sign In';password.autocomplete=next==='signup'?'new-password':'current-password';$('#error').textContent='';$('#status').hidden=true;}
 $('#register').textContent=admin?'Register for an account':roleName+' Registration / Sign Up';
 $('#register').onclick=e=>{e.preventDefault();if(busy)return;if(admin){setMode(mode==='signin'?'signup':'signin');return;}setMode(mode==='signin'?'signup':'signin');};
 $('#reset').hidden=!recover;$('#reset').onclick=()=>setMode('recover');
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;if(artistMember&&mode==='signup'){const f=$('#first_name'),l=$('#last_name'),p=$('#phone'),c=$('#confirm_password');if(!f.value.trim()||!l.value.trim()||!/^\+?[\d().\-\s]{7,40}$/.test(p.value)||c.value!==password.value||!$('#sms_opt_in').checked){$('#error').textContent='Enter first and last name, a valid phone number, matching passwords, and check SMS permission.';return;}sessionStorage.setItem('artist-profile-'+site,JSON.stringify({first_name:f.value.trim(),last_name:l.value.trim(),phone:p.value.trim(),sms_opt_in:true}));}const a=validate(email),b=validate(password);if(!a||!b){(!a?email:password).focus();return;}busy=true;const submit=$('button[type=submit]');submit.disabled=true;$('.layout').inert=true;form.setAttribute('aria-busy','true');$('.overlay').hidden=false;const label=mode==='signin'?'Signing in…':mode==='signup'?'Creating account…':'Sending reset email…';$('#loading-title').textContent=label;$('#submit-text').textContent=label;submit.querySelector('.spinner').hidden=false;$('#status').hidden=true;$('#error').textContent='';
  try{const submittedMode=mode;const cooldownKey='rr_email_retry_'+email.value.trim().toLowerCase();if(mode!=='signin'){let until=0;try{until=Number(sessionStorage.getItem(cooldownKey));}catch{}if(until>Date.now())throw Error('Please wait '+Math.ceil((until-Date.now())/1000)+' seconds before requesting another email.');}const data={email:email.value.trim(),password:password.value,captchaToken:await accountBotCheck()};const action=mode==='signin'?authenticate:mode==='signup'?signup:recover;if(!action)throw Error('This account action is not available. Contact the label for help.');const started=Date.now();let result,failure;try{result=await action(data);}catch(error){failure=error;}await new Promise(r=>setTimeout(r,Math.max(0,2000-(Date.now()-started))));if(failure)throw failure;if(submittedMode!=='signin')try{sessionStorage.setItem(cooldownKey,String(Date.now()+60000));}catch{}remember();password.value='';if(mode==='signin'){await onSuccess(result);$('#loading-title').textContent='Login Successful! Redirecting…';$('#status').textContent='Login Successful! Redirecting…';$('#status').hidden=false;await new Promise(r=>setTimeout(r,850));location.reload();return;}if(submittedMode==='signup'){busy=false;close();waitForVerification({email:data.email,site,role,resend:()=>resend?.({email:data.email}),onSignIn:()=>openSignIn({name,authenticate,signup,recover,resend,onSuccess,admin,role,site})});return;}setMode('signin');$('#status').textContent=mode==='signin'&&result?.message?result.message:'Check your email to continue. Then return here to sign in.';$('#status').hidden=false;
  }catch(error){const limited=/email.*rate.limit|rate.limit.*email/i.test(error.message||'');if(limited)try{sessionStorage.setItem('rr_email_retry_'+email.value.trim().toLowerCase(),String(Date.now()+900000));}catch{}const raw=String(error?.message||'');let friendly='We could not sign you in. Check your email and password, then try again.';if(/invalid.*login|invalid.*credentials/i.test(raw))friendly='That email or password does not match an account. Check both fields or use Forgot password.';else if(/email.*not.*confirm|confirm.*email/i.test(raw))friendly='Your email still needs verification. Open the verification email first, then sign in.';else if(/already.*register|already.*exist|user.*exist/i.test(raw))friendly='An account already uses this email. Choose Sign In or Forgot password instead.';else if(/password/i.test(raw)&&/short|least|length/i.test(raw))friendly='Your password needs at least 6 characters.';else if(/network|fetch|unavailable/i.test(raw))friendly='The sign-in service is temporarily unavailable. Check your connection and try again.';$('#error').textContent=limited?'Too many verification emails were requested. Use Continue with Google or wait before requesting another email.':friendly;password.value='';}finally{busy=false;$('.layout').inert=false;$('.overlay').hidden=true;form.removeAttribute('aria-busy');submit.disabled=false;submit.querySelector('.spinner').hidden=true;$('#submit-text').textContent=mode==='signin'?'Sign In':mode==='signup'?'Create Account':'Send Reset Email';}
 };
 brandSignIn(root,dialog,{site,name,role});dialog.showModal();dialog.focus({preventScroll:true});dialog.scrollTop=0;try{const pending=JSON.parse(sessionStorage.getItem('rr_pending_verification')||'null');if(!admin&&pending?.site===site&&pending?.role===role){close();waitForVerification({email:pending.email,site,role,resend:()=>resend?.({email:pending.email}),onSignIn:()=>openSignIn({name,authenticate,signup,recover,resend,onSuccess,admin,role,site})});}}catch{}return dialog;
}

